### ISSUE TITLE
use rclone from own package

### ISSUE THREAD

**Issue by vtolstov** [ncw/rclone#1089]
I need to sync local path t remote swift server and i don't want full rclone.
I'm try to construct Fs via swift.NewFsWithConection, but get error:
```
./main.go:48: cannot use c (type *"github.com/ncw/swift".Connection) as type *"github.com/ncw/rclone/vendor/github.com/ncw/swift".Connection in argument to "github.com/ncw/rclone/swift".NewFsWithConnection
```

**Comment by vtolstov** [comment]
Why rclone uses bundled type?

**Comment by vtolstov** [comment]
I'm remove vendored folder, but now have panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x4eeec7]

goroutine 1 [running]:
panic(0x68ba00, 0xc42000c100)                                                                                                                   /home/vtolstov/.go/src/runtime/panic.go:500 +0x1a1
github.com/ncw/rclone/vendor/github.com/Unknwon/goconfig.(*ConfigFile).GetValue(0x0, 0x6dde22, 0x5, 0x6df9b0, 0xb, 0x0, 0x0, 0x0, 0x0)
        /home/vtolstov/go/src/github.com/ncw/rclone/vendor/github.com/Unknwon/goconfig/conf.go:159 +0x67                                github.com/ncw/rclone/vendor/github.com/Unknwon/goconfig.(*ConfigFile).MustValue(0x0, 0x6dde22, 0x5, 0x6df9b0, 0xb, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0xc420051de0)
        /home/vtolstov/go/src/github.com/ncw/rclone/vendor/github.com/Unknwon/goconfig/conf.go:254 +0x57
github.com/ncw/rclone/swift.NewFsWithConnection(0x6dde22, 0x5, 0x6e291a, 0x14, 0xc4200a26e0, 0x0, 0x0, 0x68a1c0, 0x0)
        /home/vtolstov/go/src/github.com/ncw/rclone/swift/swift.go:195 +0x206
main.main()
        /home/vtolstov/main.go:49 +0xe9
```

**Comment by vtolstov** [comment]
I'm use new fs with own connection, why rclone  uses 
storageURL := fs.ConfigFile.MustValue(name, "storage_url") ?

**Comment by vtolstov** [comment]
As i understand this value can be retrived via already established connection with swift

**Comment by ncw** [comment]
Vendoring is the way to keep rclone's dependencies stable.

I don't like it particularly, but it is the best solution so far.

> I'm use new fs with own connection, why rclone uses
> storageURL := fs.ConfigFile.MustValue(name, "storage_url") ?

That is so you can override it - in normal use it will be blank and fetched from the server as you said.

**Comment by vtolstov** [comment]
ConfigFile is nil, because i don't have it (why it needed if all vars i'm already use to coonect to swift)?

**Comment by vtolstov** [comment]
```
  dfs, err := rswift.NewFsWithConnection("swift", "public/atomic/fedora", c)
  if err != nil {
    panic(err)
  }

  fmt.Printf("%#+v\n", dfs.Features())

  sfs, err := rlocal.NewFs("local", "repo/")
  if err != nil {
    panic(err)                                                                                                                            }
                                                                                                                                          fmt.Printf("%s\n", sfs)                                                                                                                                                                                                                                                         err = rfs.Sync(dfs, sfs)
  if err != nil {
    panic(err)
  }
```

**Comment by vtolstov** [comment]
the code above not works =(

**Comment by ncw** [comment]
Can you post the complete script somewhere (a gist maybe) then I can have a go with it?

**Comment by vtolstov** [comment]
@ncw thanks! https://gist.github.com/vtolstov/2ce691a3c4c627685e887485145509f2

**Comment by vtolstov** [comment]
Hi! Do you have any news ?

**Comment by ncw** [comment]
You need a call to 

    fs.LoadConfig()

Early in your main - that should fix it!

**Comment by vtolstov** [comment]
Nice! How can I modify default after loadconfig?

7 Фев 2017 г. 17:01 пользователь "Nick Craig-Wood" <notifications@github.com>
написал:

**Comment by ncw** [comment]
> Nice! How can I modify default after loadconfig?

You can change the `fs.Config` structure which is defined [here](https://github.com/ncw/rclone/blob/master/fs/config.go#L184)

**Comment by vtolstov** [comment]
Thanks!
