### ISSUE TITLE
Panic while syncing with ACD

### ISSUE THREAD

**Issue by chosenken** [ncw/rclone#1117]
Hello.  I am attempting to sync up a directory to ACD that is about 1.07Tb in size.  Since it will take a while, I left the command running in `screen` over night.  When I got on today, I see that `rclone` crashed with the following stack trace:

```
2017/02/10 14:10:38
Transferred:   221.380 GBytes (4.471 MBytes/s)
Errors:                 0
Checks:             53663
Transferred:        98268
Elapsed time:   14h5m0.8s
Transferring:
 * ...035.L3m_DAY_SCID_V3.0_anc_sst_1deg.bz2.md5: 100% done, 76 Bytes/s, ETA: 0s
 * ...054/Q2012054211300.L2_EVSCI_V1.2DR.bz2.md5: 100% done, 0 Bytes/s, ETA: 0s
 * ...2011273.L3m_DAY_SCID_V3.0_SSS_1deg.bz2.md5:  0% done, 0 Bytes/s, ETA: -
 * ...37/Q2012037.L3m_DAY_SCIA_V3.0_SSS_1deg.bz2:  0% done, 0 Bytes/s, ETA: -
 * ...73/Q2011273.L3m_DAY_SCID_V3.0_SSS_1deg.bz2: 100% done, 17.949 kBytes/s, ETA: 0s
 * ...V3/2012/058/Q2012058145600.L2_SCI_V3.0.bz2: 100% done, 5.794 MBytes/s, ETA: 0s

2017/02/10 14:11:38
Transferred:   221.482 GBytes (4.468 MBytes/s)
Errors:                 0
Checks:             53663
Transferred:        98424
Elapsed time:   14h6m0.8s
Transferring:
 * ...035/Q2015035.L3m_DAY_SCI_V3.0_SSS_1deg.bz2: 100% done, 35.708 kBytes/s, ETA: 0s
 * ...3266.L3m_7D_SCIA_V3.0_anc_sst_1deg.bz2.md5: 100% done, 0 Bytes/s, ETA: 0s
 * ...3273.L3m_7D_SCI_V3.0_SSS_bias_adj_1deg.bz2: 100% done, 84.297 kBytes/s, ETA: 0s
 * ...6.L3m_7D_SCI_V3.0_scat_wind_speed_1deg.bz2: 100% done, 93.560 kBytes/s, ETA: 0s
 * ...672013273.L3m_7D_SCI_V3.0_anc_sst_1deg.bz2: 100% done, 0 Bytes/s, ETA: 0s
 * ..._DAY_EVSCI_V1.3.5_scat_wind_speed_1deg.bz2: 100% done, 35.918 kBytes/s, ETA: 0s

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x76ef52]

goroutine 61 [running]:
panic(0xbd5160, 0xc4200120b0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ncw/rclone/oauthutil.(*TokenSource).Invalidate(0x0)
        /root/go/src/github.com/ncw/rclone/oauthutil/oauthutil.go:155 +0x22
github.com/ncw/rclone/amazonclouddrive.(*Fs).shouldRetry(0xc4202ba4d0, 0xc4269ff7a0, 0x10e23e0, 0xc420467a40, 0xc4269ff7a0, 0x10e23e0, 0xc420467a40)
        /root/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:160 +0x4e
github.com/ncw/rclone/amazonclouddrive.(*Object).readMetaData.func1(0xc42000d380, 0x76ccda, 0xc41fda63a5)
        /root/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:901 +0xf9
github.com/ncw/rclone/pacer.(*Pacer).call(0xc42000d380, 0xc424b38b40, 0xa, 0xc72aa0, 0x1)
        /root/go/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x89
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc42000d380, 0xc424b38b40, 0x5e, 0xc420b63a00)
        /root/go/src/github.com/ncw/rclone/pacer/pacer.go:357 +0x66
github.com/ncw/rclone/amazonclouddrive.(*Object).readMetaData(0xc426125f40, 0xc420467690, 0x5e)
        /root/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:902 +0x405
github.com/ncw/rclone/amazonclouddrive.(*Fs).Put(0xc4202ba4d0, 0x10e2620, 0xc4207fc460, 0x10eefc0, 0xc426125ec0, 0xc426125e80, 0x0, 0x0, 0xc420493c70)
        /root/go/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:547 +0x159
github.com/ncw/rclone/fs.Copy(0x10efb20, 0xc4202ba4d0, 0x0, 0x0, 0xc420b317a0, 0x5e, 0x10f0220, 0xc42526eb00, 0x0, 0x0)
        /root/go/src/github.com/ncw/rclone/fs/operations.go:279 +0x1169
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc42006c300, 0xc420067740, 0x10efb20, 0xc4202ba4d0, 0xc42006c3b0)
        /root/go/src/github.com/ncw/rclone/fs/sync.go:374 +0x31e
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
        /root/go/src/github.com/ncw/rclone/fs/sync.go:403 +0xad
```

The version of rclone is `rclone v1.35-DEV`, specifically built off of commit `381b845`.  It is running on a Digital Ocean machine running Ubuntu 16.04 x86-64.

The command ran is: `rclone --transfers 6 sync aquarius/ ACD:Public/SaveScience/podaac.jpl.nasa.gov/allData/aquarius`

I don't have a log with the verbose flag on, but I have restarted the command with it set, and am capturing it to a log file.  If it happens to crash again I can then provide the verbose log file.  If you need anymore information, please let me know.  Thanks!

**Comment by ncw** [comment]
Looks like I introduced that bug quite recently in bd29015022ab627a644c26b3b61a3a44f3268210

Here is a beta with a fix

http://beta.rclone.org/v1.35-80-g40c0298/ (uploaded in 15-30 mins)

Please re-open if it doesn't fix it!

Thanks

Nick
