### ISSUE TITLE
rclone panic

### ISSUE THREAD

**Issue by calisro** [ncw/rclone#1213]
I'm using the new beta and i'm seeing some errors intermittantlly in once of my processes that hasn't changed for a long time.  (same commands/remote).  This just started in one of hte new betas.  I see it on logs as far back as v1.35-137-ge2f0feeβ but i don't have logs going back further.

v1.35-153-g1cc58e4β

```
rclone --bwlimit '07:00,6M 23:00,10M' '--include=/*/*/*' move -v /data/cams robacd:/cams/
...
...
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6ff3eb]

goroutine 3304 [running]:
github.com/ncw/rclone/fs.(*asyncReader).Read(0xc426e1cea0, 0xc427472000, 0x8000, 0x8000, 0xc400000008, 0xc427253d70, 0x40d5f8)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:132 +0x4b
github.com/ncw/rclone/fs.(*Account).read(0xc42730e4d0, 0x7f3bbd8551f0, 0xc426e1cea0, 0xc427472000, 0x8000, 0x8000, 0x0, 0x0, 0xc427253e28)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/accounting.go:437 +0xa5
github.com/ncw/rclone/fs.(*Account).Read(0xc42730e4d0, 0xc427472000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/accounting.go:467 +0x160
io.(*multiReader).Read(0xc425cd19c0, 0xc427472000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/io/multi.go:26 +0xcf
io.copyBuffer(0x11a9740, 0xc425cd1d60, 0x11a9600, 0xc425cd19c0, 0xc427472000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/io/io.go:390 +0x100
io.Copy(0x11a9740, 0xc425cd1d60, 0x11a9600, 0xc425cd19c0, 0x17, 0x11a9740, 0xc425cd1d60)
        /home/travis/.gimme/versions/go1.8.linux.amd64/src/io/io.go:360 +0x68
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*NodesService).putOrOverwrite.func1(0xc420658070, 0xc425eef2c0, 0x55, 0xc4250ee8d0, 0xc426ec8d20, 0xc420233812, 0x17, 0x11a9600, 0xc425cd19c0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:649 +0xf2
created by github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*NodesService).putOrOverwrite
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:654 +0x3d2

```

**Comment by ncw** [comment]
Thanks for reporting this.

It looks like a mistake in the buffer logic I introduced recently...

Looks like I'll have to push back the release until I've reproduced it and fixed it :-(

**Comment by ncw** [comment]
I believe I have fixed this - would appreciate you testing it though.

http://beta.rclone.org/v1.35-162-gb2a4ea9/ (uploaded in 15-30 mins)

Please re-open if it doesn't fix the problem!

Thanks

Nick

**Comment by calisro** [comment]
I'll give it a go.

**Comment by aslefnad** [comment]
I had the same problem and for me this update fixed it.

**Comment by calisro** [comment]
I haven't had a recurrence.  So that's good.
