### ISSUE TITLE
Rename Panic

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1226]
Looks like a panic in the code. Maybe something to do with crypt? Logs below.

This is a Crypt mount on ACD.

> What is your rclone version (eg output from `rclone -V`)

v1.35-99-g6fc114d

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu / Debian based container

> Which cloud storage system are you using? (eg Google Drive)

ACD

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Filebot rename script (mv command at the os level)

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2017-03-09T03:44:32.718751915Z 2017/03/09 03:44:32 fuse: panic in handler for Rename [ID=0x1a59809 Node=0x3b2 Uid=0 Gid=0 Pid=1782] from "Star Trek The Next Generation - S01E24 - We'll Always Have Paris [1080p, x264, AAC].mp4" to dirnode 0x3b2 "Star Trek The Next Generation - S01E24 - We'll Always Have Paris.mp4": runtime error: invalid memory address or nil pointer dereference
2017-03-09T03:44:32.718783866Z goroutine 32210461 [running]:
2017-03-09T03:44:32.718788757Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x10eeb60, 0xc457256780, 0xc44a707ea8, 0xc44a707dff)
2017-03-09T03:44:32.718799151Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1d9
2017-03-09T03:44:32.718802875Z panic(0xbd3c80, 0xc420012060)
2017-03-09T03:44:32.718805455Z 	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:458 +0x243
2017-03-09T03:44:32.718808153Z github.com/ncw/rclone/crypt.(*Object).Remote(0xc42452ace0, 0xc42452ad60, 0x513130)
2017-03-09T03:44:32.718810831Z 	/home/travis/gopath/src/github.com/ncw/rclone/crypt/crypt.go:398 +0x29
2017-03-09T03:44:32.718813492Z github.com/ncw/rclone/cmd/mount.(*Dir).addObject(0xc420fbe000, 0x7fbfbfaf3d00, 0xc42452ace0, 0x0, 0x0, 0x10f3be0)
2017-03-09T03:44:32.718816326Z 	/home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:55 +0xa7
2017-03-09T03:44:32.718819632Z github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc420fbe000, 0x7fbfbfcb4970, 0xc431a303c0, 0xc457256780, 0x10e62a0, 0xc420fbe000, 0x0, 0x10e8b20)
2017-03-09T03:44:32.718822433Z 	/home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:411 +0x7d9
2017-03-09T03:44:32.718825540Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc42132c000, 0x7fbfbfcb4970, 0xc431a303c0, 0x10e62a0, 0xc420fbe000, 0xc44ad28bc0, 0x10eeb60, 0xc457256780, 0xc44a707ea8, 0xc454673766, ...)
2017-03-09T03:44:32.718828584Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x27e0
2017-03-09T03:44:32.718831553Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc42132c000, 0x10eeb60, 0xc457256780)
2017-03-09T03:44:32.718834163Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x4a3
2017-03-09T03:44:32.718836772Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc42132c000, 0x10eeb60, 0xc457256780)
2017-03-09T03:44:32.718839349Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
2017-03-09T03:44:32.718841875Z created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
2017-03-09T03:44:32.718844376Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x3e4
```

**Comment by ncw** [comment]
How repeatable is this?  Can you get it do do it whenever you like?

I tried to reproduce it but I couldn't yet.

----

This looks like `o.Object` was nil in `crypt/crypt.go`

```go
// Remote returns the remote path
func (o *Object) Remote() string {
	remote := o.Object.Remote() // o.Object nil here --------------------
	decryptedName, err := o.f.cipher.DecryptFileName(remote)
```

**Comment by tcf909** [comment]
Basically happens every time I run a filebot rename command against a large set of files. Just happened again:

```
2017-03-09T20:15:34.273097255Z 2017/03/09 20:15:34 fuse: panic in handler for Rename [ID=0x791c1 Node=0x1 Uid=0 Gid=0 Pid=7753] from "Greys.Anatomy.S09E23.HDTV.x264-LOL.mp4" to dirnode 0x3943 "Grey's Anatomy - S09E23 - Readiness is All.mp4": runtime error: invalid memory address or nil pointer dereference
2017-03-09T20:15:34.273140410Z goroutine 709832 [running]:
2017-03-09T20:15:34.273153961Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x10eeb60, 0xc422cad9e0, 0xc4241afea8, 0xc4241afdff)
2017-03-09T20:15:34.273160076Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1d9
2017-03-09T20:15:34.273164780Z panic(0xbd3c80, 0xc420012060)
2017-03-09T20:15:34.273168878Z 	/home/travis/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:458 +0x243
2017-03-09T20:15:34.273194297Z github.com/ncw/rclone/crypt.(*Object).Remote(0xc421e2eb60, 0xc421e2eba0, 0x513130)
2017-03-09T20:15:34.273199816Z 	/home/travis/gopath/src/github.com/ncw/rclone/crypt/crypt.go:398 +0x29
2017-03-09T20:15:34.273204091Z github.com/ncw/rclone/cmd/mount.(*Dir).addObject(0xc422d19180, 0x7fbff957f0c0, 0xc421e2eb60, 0x0, 0x0, 0x10f3be0)
2017-03-09T20:15:34.273208492Z 	/home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:55 +0xa7
2017-03-09T20:15:34.273214217Z github.com/ncw/rclone/cmd/mount.(*Dir).Rename(0xc420263420, 0x7fbff97d9c00, 0xc421234bc0, 0xc422cad9e0, 0x10e62a0, 0xc422d19180, 0x0, 0x10e8b20)
2017-03-09T20:15:34.273219155Z 	/home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:411 +0x7d9
2017-03-09T20:15:34.273224266Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc4203da0c0, 0x7fbff97d9c00, 0xc421234bc0, 0x10e62a0, 0xc420263420, 0xc4213feac0, 0x10eeb60, 0xc422cad9e0, 0xc4241afea8, 0x0, ...)
2017-03-09T20:15:34.273229349Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1335 +0x27e0
2017-03-09T20:15:34.273232699Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc4203da0c0, 0x10eeb60, 0xc422cad9e0)
2017-03-09T20:15:34.273235341Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x4a3
2017-03-09T20:15:34.273238018Z github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc4203da0c0, 0x10eeb60, 0xc422cad9e0)
2017-03-09T20:15:34.273241037Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
2017-03-09T20:15:34.273243768Z created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
2017-03-09T20:15:34.273246305Z 	/home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:426 +0x3e4
```

**Comment by ncw** [comment]
I think this will probably fix the panic - the rename will fail instead.  Can you give it a test please?

http://beta.rclone.org/v1.35-164-g488353c/ (uploaded in 15-30 mins)

If it doesn't can you attach a log with `-vv` please?  Thanks

**Comment by tcf909** [comment]
Seems good to go now Nick. Thanks.

**Comment by ncw** [comment]
Thanks for testing :-)
