### ISSUE TITLE
copyto places files in incorrect place for non-existent directory

### ISSUE THREAD

**Issue by tcf909** [ncw/rclone#1231]
Similar to #281 but for encrypted backends:

I'm running in to issues with spaces in names when using encrypted remotes.

I use copyto "TARGET:dir/to copy/into/file.whatever" and in the logs I see:

```
Encrypted amazon drive root 'Vault/dmi0e2fbj6btggkj33t5dtqmo4/j4jctgmgj50nsvqtbd2gb0o8ig/4nbenmipf0htppnrq2hmqaqk40/7em7kl21js9ribn89uaqsr0nkc': Modify window not supported
```

But that directory doesn't end up existing, rather a file gets created next to "Vault/" in my amazon drive so the dir listing looks like:
```
Vault/
etltv0troceojn8bb67iqal3vnbt66jg5vcnoqmv1i2i1e18442nhdv1ob09c03edpcdedlcuf3aoa0h0v28puvbilivtade7rj4r40
```

The newly copied file actually being the etltv0troc... file (which is outside of the encrypted root and not part of the directory path it should be in)

Subsequent attempts to copyto the same file returns with "file does not need to be copied", but its referencing this out of root file.

rclone version: rclone v1.35-164-g488353cβ

**Comment by tcf909** [comment]
It actually looks like all copyto isn't working with encrypted remote. It stores the file in an encrypted file outside of the Vault/ Root that is set:

```
rclone --config /etc/rclone/rclone.conf copyto '/data/.Local/Shows/Arrow/Season 02/Arrow - S02E03 - Broken Dolls [480p, x264, AAC, HDTV].mp4' ACD_VAULT:Media/Shows/test.mp4 -vvvvvv --stats 30s --crypt-show-mapping
2017/03/12 08:01:26 DEBUG : rclone: Version "v1.35-164-g488353cβ" starting with parameters ["rclone" "--config" "/etc/rclone/rclone.conf" "copyto" "/data/.Local/Shows/Arrow/Season 02/Arrow - S02E03 - Broken Dolls [480p, x264, AAC, HDTV].mp4" "ACD_VAULT:Media/Shows/test.mp4" "-vvvvvv" "--stats" "30s" "--crypt-show-mapping"]
2017/03/12 08:01:26 DEBUG : ACD: Saved new token in config file
2017/03/12 08:01:27 INFO  : Encrypted amazon drive root 'Vault/dmi0e2fbj6btggkj33t5dtqmo4/j4jctgmgj50nsvqtbd2gb0o8ig': Modify window not supported
2017/03/12 08:01:27 DEBUG : Arrow - S02E03 - Broken Dolls [480p, x264, AAC, HDTV].mp4: Sizes identical
2017/03/12 08:01:27 DEBUG : Arrow - S02E03 - Broken Dolls [480p, x264, AAC, HDTV].mp4: Unchanged skipping
2017/03/12 08:01:27 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       800ms
2017/03/12 08:01:27 DEBUG : Go routines at exit 11
2017/03/12 08:01:27 DEBUG : rclone: Version "v1.35-164-g488353cβ" finishing with parameters ["rclone" "--config" "/etc/rclone/rclone.conf" "copyto" "/data/.Local/Shows/Arrow/Season 02/Arrow - S02E03 - Broken Dolls [480p, x264, AAC, HDTV].mp4" "ACD_VAULT:Media/Shows/test.mp4" "-vvvvvv" "--stats" "30s" "--crypt-show-mapping"]
```

rclone.conf:
```
[ACD_VAULT]
type = crypt
remote = ACD:Vault
filename_encryption = standard
***REST OMITTED***
```

**Comment by tcf909** [comment]
It looks like if you do not include a root slash in the target the above will happen.

So instead of ACD_VAULT:Media (which is what I typically use), if I use ACD_VAULT:/Media everything seems to work ok.

**Comment by tcf909** [comment]
Actually it looks like this happens ANY time the destination directory doesn't already exist. Once the destination directory is created it seems to work as expected.

**Comment by ncw** [comment]
I've managed to confirm this.

It doesn't seem to need a space in the filename.  This seems to go wrong on google drive too
```
$ rclone -vv copyto hello.txt secretacd:non-exist-dir/hello2.txt
$ rclone ls secretacd:non-exist-dir
2017/03/13 12:07:47 Failed to ls: directory not found
$ rclone lsl --max-depth 1 acd:
       54 2017-03-13 11:51:05.755000000 gttofhvjcn6226aka4trpppv4k
```

This also goes wrong without crypt

```
$ rclone -vv copyto hello.txt acd:non-exist-dir/hello2.txt
2017/03/13 12:09:14 DEBUG : rclone: Version "v1.35-169-g320c53e" starting with parameters ["rclone" "-vv" "copyto" "hello.txt" "acd:non-exist-dir/hello2.txt"]
2017/03/13 12:09:15 INFO  : amazon drive root 'non-exist-dir': Modify window not supported
2017/03/13 12:09:15 DEBUG : hello.txt: Couldn't find file - need to transfer
2017/03/13 12:09:16 INFO  : hello.txt: Copied (new)
2017/03/13 12:09:16 INFO  : 
Transferred:      6 Bytes (5 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.1s
2017/03/13 12:09:16 DEBUG : Go routines at exit 12
2017/03/13 12:09:16 DEBUG : rclone: Version "v1.35-169-g320c53e" finishing with parameters ["rclone" "-vv" "copyto" "hello.txt" "acd:non-exist-dir/hello2.txt"]
$ rclone ls acd:non-exist-dir
2017/03/13 12:09:25 Failed to ls: directory not found
$ rclone lsl --max-depth 1 acd:
        6 2017-03-13 12:09:15.951000000 hello2.txt
```

**Comment by tcf909** [comment]
I can confirm this is happening with the mount command as well.

I mounted ACD_VAULT:Media

```
[ACD_VAULT]
type = crypt
remote = ACD:TEST
filename_encryption = off
password = ***
password2 = ***
```

```
ls ACD:
TEST (Empty)
```

So the TEST was there (the root of the CRYPT), but the Media directory in TEST was missing.

Running the command:
```
echo 123 > abc
```

Resulted in:
```
ls ACD:
TEST (Empty)
abc.bin
```

**Comment by ncw** [comment]
This should fix all the above!  If it doesn't, please re-open.

http://beta.rclone.org/v1.35-174-g9b07d32/ (uploaded in 15-30 mins)

**Comment by tcf909** [comment]
Thanks Nick. I'll give it a try later today.

**Comment by tcf909** [comment]
```
+ /usr/local/bin/rclone mount ACD_VAULT:/Media /data/.Vault --config /etc/rclone/rclone.conf -v --max-read-ahead 200M --buffer-size 200M --allow-other
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x814023, 0x9)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:596 +0x70
runtime.newosproc(0x1442002a000, 0x1442003a000)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/os_linux.go:163 +0x164
runtime.newm(0x848e20, 0x0)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1628 +0x110
runtime.main.func1()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:126 +0x28
runtime.systemstack(0xccdd00)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:241 +0x90
runtime.mstart()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:190 +0x8 fp=0x14420026780 sp=0x14420026770
runtime.main()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/proc.go:127 +0x58 fp=0x144200267d0 sp=0x14420026780
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_arm64.s:981 +0x4 fp=0x144200267d0 sp=0x144200267d0
```

Running 174 beta. 164 doesn't throw in the same container.

**Comment by ncw** [comment]
> runtime: failed to create new OS thread (have 2 already; errno=22)

Looks like the container is limiting the number of threads?  rclone can potentially use lots of threads.

**Comment by tcf909** [comment]
No limit on threads. Also, exact same container using 164, never have a
problem (tons and tons of different type of IO last couple of weeks 20+ TB).

**Comment by ncw** [comment]
@tcf909 can you create a new issue about this please?

Can you describe exactly how you are running the binary in the ticket too please?
