### ISSUE TITLE
Fatal error: runtime: out of memory crash

### ISSUE THREAD

**Issue by DairyDTP** [ncw/rclone#1516]
Memory usage for rclone balloons to consume 100% of memory, 32GB in this case, for a 7 GB file.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-231-g575e779bβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 64 bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rclone -vv --dump-headers --dump-bodies copy ~/file.mov acd:Videos/

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
:~/rclone-v1.36-231-g575e779bβ-linux-amd64$ ./rclone -vv --dump-headers --dump-bodies copy ~/Videos/file.mov acdde:Videos/
2017/07/03 19:40:05 DEBUG : rclone: Version "v1.36-231-g575e779bβ" starting with parameters ["./rclone" "-vv" "--dump-headers" "--dump-bodies" "copy" "/home/user/Videos/file.mov" "acdde:Videos/"]
2017/07/03 19:40:05 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:05 DEBUG : HTTP REQUEST (req 0xc42015be00)
2017/07/03 19:40:05 DEBUG : GET /drive/v1/account/endpoint HTTP/1.1
Host: drive.amazonaws.com
User-Agent: rclone/v1.36-231-g575e779bβ
Authorization: XXXX
Accept-Encoding: gzip

2017/07/03 19:40:05 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : HTTP RESPONSE (req 0xc42015be00)
2017/07/03 19:40:06 DEBUG : HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jul 2017 17:40:06 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: a6d2cfe6-6016-11e7-8324-0738c36dfa94

{"contentUrl":"https://content-eu.drive.amazonaws.com/cdproxy/","customerExists":true,"metadataUrl":"https://cdws.eu-west-1.amazonaws.com/drive/v1/"}
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : HTTP REQUEST (req 0xc420115300)
2017/07/03 19:40:06 DEBUG : GET /drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue HTTP/1.1
Host: cdws.eu-west-1.amazonaws.com
User-Agent: rclone/v1.36-231-g575e779bβ
Authorization: XXXX
Accept-Encoding: gzip

2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : HTTP RESPONSE (req 0xc420115300)
2017/07/03 19:40:06 DEBUG : HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jul 2017 17:40:06 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: a6ea013e-6016-11e7-bdc5-a394ae1f8023

{"data":[{"isRoot":true,"eTagResponse":"3KZFsWFFVSc","id":"...","kind":"FOLDER","version":3,"labels":[],"createdDate":"2014-11-01T00:02:49.377Z","createdBy":"CloudDriveFiles","restricted":false,"modifiedDate":"2017-07-02T20:11:39.997Z","isShared":false,"parents":[],"status":"AVAILABLE"}],"count":1}
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : HTTP REQUEST (req 0xc420115800)
2017/07/03 19:40:06 DEBUG : GET /drive/v1/nodes?filters=parents%3A%22aReDrcnnSO6HkAWvenzetA%22+AND+name%3A%22Videos%22 HTTP/1.1
Host: cdws.eu-west-1.amazonaws.com
User-Agent: rclone/v1.36-231-g575e779bβ
Authorization: XXXX
Accept-Encoding: gzip

2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : HTTP RESPONSE (req 0xc420115800)
2017/07/03 19:40:06 DEBUG : HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jul 2017 17:40:06 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: a6f17b7c-6016-11e7-af84-f1828d01e40c

{"data":[{"eTagResponse":"lB9qcZasUrc","id":"...","kind":"FOLDER","version":25,"labels":[],"createdDate":"2017-07-02T20:11:39.986Z","createdBy":"ACD Profile-A2NI5C1NWIPJBY","restricted":false,"modifiedDate":"2017-07-03T09:34:33.314Z","name":"Videos","isShared":false,"parents":["aReDrcnnSO6HkAWvenzetA"],"status":"AVAILABLE"}],"count":1}
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 INFO  : amazon drive root 'Videos': Modify window not supported
2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : HTTP REQUEST (req 0xc4202d6300)
2017/07/03 19:40:06 DEBUG : GET /drive/v1/nodes?filters=parents%3A9vzpw2u4TdyyajOdxvGEXQ HTTP/1.1
Host: cdws.eu-west-1.amazonaws.com
User-Agent: rclone/v1.36-231-g575e779bβ
Authorization: XXXX
Accept-Encoding: gzip


2017/07/03 19:40:06 DEBUG : HTTP RESPONSE (req 0xc4202d6300)
2017/07/03 19:40:06 DEBUG : HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jul 2017 17:40:06 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: a6fa7ca0-6016-11e7-a507-53f3e83f944f

{"data":[{....}


...

2017/07/03 19:40:06 INFO  : amazon drive root 'Videos': Waiting for checks to finish
2017/07/03 19:40:06 INFO  : amazon drive root 'Videos': Waiting for transfers to finish
2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : HTTP REQUEST (req 0xc420115500)
2017/07/03 19:40:06 DEBUG : GET /drive/v1/nodes?filters=parents%3A%229vzpw2u4TdyyajOdxvGEXQ%22+AND+name%3A%22file.mov%22 HTTP/1.1
Host: cdws.eu-west-1.amazonaws.com
User-Agent: rclone/v1.36-231-g575e779bβ
Authorization: XXXX
Accept-Encoding: gzip

2017/07/03 19:40:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:40:06 DEBUG : HTTP RESPONSE (req 0xc420115500)
2017/07/03 19:40:06 DEBUG : HTTP/1.1 200 OK
Cache-Control: no-store
Connection: keep-alive
Content-Type: application/json
Date: Mon, 03 Jul 2017 17:40:06 GMT
Pragma: no-cache
Server: Server
Vary: User-Agent
X-Amzn-Requestid: a70725f0-6016-11e7-9946-4d48d3ce7496

{"data":[],"count":0}
2017/07/03 19:40:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/07/03 19:41:06 INFO  : 
Transferred:   1.171 GBytes (19.767 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.6s
Transferring:
 *                                    file.mov: 15% done, 16.056 MBytes/s, ETA: 6m38s

2017/07/03 19:42:06 INFO  : 
Transferred:   2.149 GBytes (18.242 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.6s
Transferring:
 *                                    file.mov: 28% done, 9.460 MBytes/s, ETA: 9m31s

2017/07/03 19:43:06 INFO  : 
Transferred:   4.000 GBytes (22.676 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.6s
Transferring:
 *                                    file.mov: 53% done, 12.106 MBytes/s, ETA: 4m49s

2017/07/03 19:44:06 INFO  : 
Transferred:   4.385 GBytes (18.661 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      4m0.6s
Transferring:
 *                                    file.mov: 59% done, 19.087 MBytes/s, ETA: 2m43s

2017/07/03 19:45:06 INFO  : 
Transferred:   7.424 GBytes (25.288 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      5m0.6s
Transferring:
 *                                    file.mov: 100% done, 33.187 MBytes/s, ETA: 0s

2017/07/03 19:46:06 INFO  : 
Transferred:   7.424 GBytes (21.080 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      6m0.6s
Transferring:
 *                                    file.mov: 100% done, 621.503 kBytes/s, ETA: 0s

2017/07/03 19:48:08 INFO  : 
Transferred:   7.424 GBytes (15.745 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      8m2.8s
Transferring:
 *                                    file.mov: 100% done, 19.379 kBytes/s, ETA: 0s

2017/07/03 19:48:10 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/07/03 19:48:10 DEBUG : HTTP REQUEST (req 0xc4202d6300)
2017/07/03 19:49:06 INFO  : 
Transferred:   7.424 GBytes (14.062 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      9m0.6s
Transferring:
 *                                    file.mov: 100% done, 414 Bytes/s, ETA: 0s

2017/07/03 19:50:06 INFO  : 
Transferred:   7.424 GBytes (12.657 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     10m0.6s
Transferring:
 *                                    file.mov: 100% done, 7 Bytes/s, ETA: 0s

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xe451db, 0x16)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xcef0880000, 0x1db440000, 0x814300, 0x1382058)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1368f40, 0x1db440000, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x1368f40, 0xeda1d, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x1368f40, 0xeda1d, 0x800000008)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x1368f40, 0xeda1d, 0x100000000, 0xc42001e528)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0xc42049bf10)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x1368f40, 0xeda1d, 0x100000000, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0x1db439c0c, 0x451400, 0xc4200de900)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/malloc.go:807 +0x93
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/malloc.go:702 +0x3e
runtime.systemstack(0xc420020c00)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/proc.go:1132

goroutine 80 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:281 fp=0xc4204cee88 sp=0xc4204cee80
runtime.mallocgc(0x1db439c0c, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/malloc.go:703 +0x930 fp=0xc4204cef28 sp=0xc4204cee88
runtime.rawstring(0x1db439c0c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/string.go:237 +0x85 fp=0xc4204cef58 sp=0xc4204cef28
runtime.rawstringtmp(0x0, 0x1db439c0c, 0xc4204b2000, 0xc4204cefe0, 0x4ba5a1, 0x134bc00, 0xe10360)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/string.go:107 +0x78 fp=0xc4204cef98 sp=0xc4204cef58
runtime.slicebytetostring(0x0, 0xcd153dc000, 0x1db439c0c, 0x1db43a000, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/string.go:89 +0x3e fp=0xc4204ceff0 sp=0xc4204cef98
fmt.Sprintf(0xe30519, 0x2, 0xc4204cf228, 0x1, 0x1, 0x7f7fb64da4b0, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/fmt/print.go:197 +0x96 fp=0xc4204cf048 sp=0xc4204ceff0
github.com/ncw/rclone/fs.logPrintf(0xc9c7a62007, 0x0, 0x0, 0xe30519, 0x2, 0xc4204cf228, 0x1, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/log.go:95 +0x66 fp=0xc4204cf0c0 sp=0xc4204cf048
github.com/ncw/rclone/fs.Debugf(0x0, 0x0, 0xe30519, 0x2, 0xc4204cf228, 0x1, 0x1)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/log.go:141 +0x87 fp=0xc4204cf110 sp=0xc4204cf0c0
github.com/ncw/rclone/fs.(*Transport).RoundTrip(0xc420222940, 0xc4202d6300, 0xc4202d6300, 0x0, 0xc4204e6530)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/http.go:230 +0x351 fp=0xc4204cf2b8 sp=0xc4204cf110
github.com/ncw/rclone/vendor/golang.org/x/oauth2.(*Transport).RoundTrip(0xc4201fd890, 0xc4202d6100, 0xc4201fd890, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/golang.org/x/oauth2/transport.go:48 +0xda fp=0xc4204cf330 sp=0xc4204cf2b8
net/http.send(0xc4202d6100, 0x12fc1c0, 0xc4201fd890, 0x0, 0x0, 0x0, 0x0, 0x8, 0xc42000c0f0, 0x40fd78)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/net/http/client.go:249 +0x162 fp=0xc4204cf450 sp=0xc4204cf330
net/http.(*Client).send(0xc4201fd8c0, 0xc4202d6100, 0x0, 0x0, 0x0, 0xc42000c0f0, 0x0, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/net/http/client.go:173 +0x108 fp=0xc4204cf4d0 sp=0xc4204cf450
net/http.(*Client).Do(0xc4201fd8c0, 0xc4202d6100, 0x1, 0x7f7fb64da4b0, 0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/net/http/client.go:595 +0x254 fp=0xc4204cf640 sp=0xc4204cf4d0
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*Client).Do(0xc4201bb380, 0xc4202d6100, 0xe04ac0, 0xc42000c0c8, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/client.go:138 +0x69 fp=0xc4204cf6c8 sp=0xc4204cf640
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*NodesService).putOrOverwrite(0xc42000c2a0, 0x12fc940, 0xc42043a420, 0xe31163, 0x4, 0xe4b619, 0x1c, 0xc420424bf1, 0xa, 0xc420408500, ...)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:674 +0x55c fp=0xc4204cf820 sp=0xc4204cf6c8
github.com/ncw/rclone/vendor/github.com/ncw/go-acd.(*Folder).Put(0xc42000c030, 0x12fb740, 0xc4202c44d0, 0xc420424bf1, 0xa, 0xc4204cf928, 0xc4204cf9e8, 0x0, 0xc4204cf9f0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/ncw/go-acd/nodes.go:699 +0x279 fp=0xc4204cf8f8 sp=0xc4204cf820
github.com/ncw/rclone/amazonclouddrive.(*Fs).Put.func1(0xc42021c4e0, 0xc420424bf1, 0xc420276820)
	/home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:575 +0x133 fp=0xc4204cfa08 sp=0xc4204cf8f8
github.com/ncw/rclone/pacer.(*Pacer).call(0xc42021c4e0, 0xc420308120, 0x1, 0x1, 0xc420308120)
	/home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:334 +0x71 fp=0xc4204cfac8 sp=0xc4204cfa08
github.com/ncw/rclone/pacer.(*Pacer).CallNoRetry(0xc42021c4e0, 0xc420308120, 0xa, 0xc4200d8f01)
	/home/travis/gopath/src/github.com/ncw/rclone/pacer/pacer.go:366 +0x3e fp=0xc4204cfb00 sp=0xc4204cfac8
github.com/ncw/rclone/amazonclouddrive.(*Fs).Put(0xc42021c5a0, 0x12fb740, 0xc4202c44d0, 0x7f7fb6404620, 0xc4202aa9c0, 0xc4203fa0c0, 0x1, 0x1, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/ncw/rclone/amazonclouddrive/amazonclouddrive.go:583 +0x530 fp=0xc4204cfc30 sp=0xc4204cfb00
github.com/ncw/rclone/fs.Copy(0x130b040, 0xc42021c5a0, 0x0, 0x0, 0xc420424bf1, 0xa, 0x130b940, 0xc4202aa9c0, 0x582057b082984164, 0xaa553e49c01221e9)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:321 +0x123d fp=0xc4204cfe80 sp=0xc4204cfc30
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc4204c36c0, 0xc42021d200, 0x130b040, 0xc42021c5a0, 0xc4204c3770)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:374 +0x31e fp=0xc4204cffb8 sp=0xc4204cfe80
runtime.goexit()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4204cffc0 sp=0xc4204cffb8
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:403 +0xad

goroutine 1 [semacquire, 10 minutes]:
sync.runtime_Semacquire(0xc4204c377c)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/sema.go:47 +0x34
sync.(*WaitGroup).Wait(0xc4204c3770)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/sync/waitgroup.go:131 +0x7a
github.com/ncw/rclone/fs.(*syncCopyMove).stopTransfers(0xc4204c36c0)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:411 +0x9d
github.com/ncw/rclone/fs.(*syncCopyMove).run(0xc4204c36c0, 0xc42021c5a0, 0x130b8c0)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:726 +0x4a9
github.com/ncw/rclone/fs.runSyncCopyMove(0x130b040, 0xc42021c5a0, 0x130b8c0, 0xc42021bb90, 0x450000, 0xc420567b00, 0xc420567b08)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:1005 +0x13a
github.com/ncw/rclone/fs.CopyDir(0x130b040, 0xc42021c5a0, 0x130b8c0, 0xc42021bb90, 0xc42021cf60, 0xc42021cf60)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/sync.go:1015 +0x50
github.com/ncw/rclone/cmd/copy.glob..func1.1(0xc42021cf60, 0xc420567b80)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/copy/copy.go:60 +0x45
github.com/ncw/rclone/cmd.Run(0xc420220101, 0x1357700, 0xc4204cdcd0)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:225 +0x8c
github.com/ncw/rclone/cmd/copy.glob..func1(0x1357700, 0xc420228370, 0x2, 0x5)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/copy/copy.go:61 +0x10d
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x1357700, 0xc42021c0c0, 0x5, 0x6, 0x1357700, 0xc42021c0c0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:660 +0x23a
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1356a40, 0xc420228320, 0x0, 0x0)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:735 +0x339
github.com/ncw/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(0x1356a40, 0x0, 0x20)
	/home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/spf13/cobra/command.go:694 +0x2b
main.main()
	/home/travis/gopath/src/github.com/ncw/rclone/rclone.go:15 +0x31

goroutine 5 [syscall, 10 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive, 10 minutes]:
github.com/ncw/rclone/oauthutil.(*Renew).renewOnExpiry(0xc4201fd920)
	/home/travis/gopath/src/github.com/ncw/rclone/oauthutil/renew.go:39 +0x5b
created by github.com/ncw/rclone/oauthutil.NewRenew
	/home/travis/gopath/src/github.com/ncw/rclone/oauthutil/renew.go:28 +0xa7

goroutine 70 [select]:
github.com/ncw/rclone/cmd.StartStats.func1(0xc42021cf60)
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:286 +0x12b
created by github.com/ncw/rclone/cmd.StartStats
	/home/travis/gopath/src/github.com/ncw/rclone/cmd/cmd.go:294 +0x7b

goroutine 29 [select]:
github.com/ncw/rclone/fs.(*Account).averageLoop(0xc4202c44d0)
	/home/travis/gopath/src/github.com/ncw/rclone/fs/accounting.go:411 +0x2df
created by github.com/ncw/rclone/fs.NewAccountSizeName
	/home/travis/gopath/src/github.com/ncw/rclone/fs/accounting.go:339 +0x1b7
````

**Comment by DairyDTP** [comment]
Maybe occurred because of parallel Amazon Cloud to Amazon Cloud sync - will rclone load all file data into memory?

**Comment by ncw** [comment]
Rclone normally streams everything however I think `--dump-bodies` will store a copy of the data in RAM, possibly multiple copies as it formats it for output.

**Comment by DairyDTP** [comment]
You're right - removing dump-bodies reduces memory usage dramatically. However, I pasted almost the entire output of the program above, minus some file names. For not actually printing any of the actual file data, why use that memory at all?

**Comment by ncw** [comment]
> However, I pasted almost the entire output of the program above, minus some file names. For not actually printing any of the actual file data, why use that memory at all?

It printed the bodies of the other requests.  I think it ran out of memory before printing the body of the enormous file.

I agree this isn't idea, but --dump-bodies is usually used for debugging small files or JSON transactions - using it to dump multi GB files isn't a use case I've optimized for!

**Comment by ncw** [comment]
I'm not going to fix this, so I'll add a small note to the docs about the behavour.
