### ISSUE TITLE
Use rclone to manage aliyun

### ISSUE THREAD

**Issue by luolibin** [ncw/rclone#1641]
hello，I'm a newbee from China.
I recently wanted to use rclone to manage Alibaba‘s aliyun,aliyun is similar to other cloud drive,but I don't know how to add source files.

**Comment by ncw** [comment]
I'm not sure what API aliyun uses. It looks like it might be s3 compatible - the docs aren't clear.  Try using `rclone config` with the s3 module - does that work?

**Comment by luolibin** [comment]
I think it should be necessary to write a .go file，I'm trying edit it.

**Comment by ncw** [comment]
Make sure you read the [CONTRIBUTING](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md) file, in particular the sections on making a new remote!  Good luck and let me know if you need help.

**Comment by luolibin** [comment]
hi,I have finished writing oss.go files and i'm testing it for the function. I found the copy method got some bugs，when I copy a file to the new bucket,it can create a bucket ,but can't copy the file.
I don't know how to solve this problem.Can you help me.

C:\rclone>rclone copy nihao.txt oss:luolibin333
bucket:  luolibin333
directory:
path:  luolibin333
endpoint:  oss-cn-hangzhou.aliyuncs.com
accessID:  ........
accessKey:  .........
src: nihao.txt
dir:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xc30787]

goroutine 33 [running]:
github.com/ncw/rclone/oss.(*Fs).Mkdir(0xc0420e3280, 0x0, 0x0, 0x0, 0x0)
        C:/GOPATH/src/github.com/ncw/rclone/oss/oss.go:725 +0x1b7
github.com/ncw/rclone/oss.(*Object).Update(0xc0422ce100, 0x137c820, 0xc0422d80b0
, 0x1dc0050, 0xc0422aa840, 0xc0422d6120, 0x1, 0x1, 0xc042271bf0, 0x70e0b0)
        C:/GOPATH/src/github.com/ncw/rclone/oss/oss.go:617 +0x5c
github.com/ncw/rclone/oss.(*Fs).Put(0xc0420e3280, 0x137c820, 0xc0422d80b0, 0x1dc
0050, 0xc0422aa840, 0xc0422d6120, 0x1, 0x1, 0x0, 0x2, ...)
        C:/GOPATH/src/github.com/ncw/rclone/oss/oss.go:692 +0x1ad
github.com/ncw/rclone/fs.Copy(0x138b380, 0xc0420e3280, 0x0, 0x0, 0xc042290240, 0
x9, 0x138b200, 0xc0422aa840, 0x0, 0x0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/operations.go:323 +0x11e6
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc04211ea80, 0xc0422323
c0, 0x138b380, 0xc0420e3280, 0xc04211eb50)
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:377 +0x33b
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:406 +0xa6

**Comment by luolibin** [comment]
I recently made a new remote to support a new cloud storage（The cloud storage is similar to s3, I imitate s3.go wrote the .go file）.But I met some problem with the copy method (mkdir,ls,lsd,rmdir and so on are good except for sync) .

     If I copy a file between bucket in the same region,it can't work，There is an error like this：
    C:\rclone>rclone copy oss:nishinamemei/notes.txt oss:luolibin321
    bucket:  nishinamemei
    directory:  notes.txt
    path:  nishinamemei/notes.txt
    endpoint:  xxxxxxx
    accessID: xxxxx
    accessKey:  xxxxx
    bucket:  luolibin321
    directory:
    path:  luolibin321
    endpoint:  oss-cn-hangzhou.aliyuncs.com
    accessID:  LTAIGvAl2UDOCPha
    accessKey:  FVZ0UOkBaXPhMDb2lqvhX6DdpiIaa0
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x58 pc=0x72ad68]

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x72ad68]

goroutine 46 [running]:
github.com/ncw/rclone/fs.Copy(0x138b380, 0xc04227e100, 0x0, 0x0, 0xc0422787a6, 0x9, 0x138b400, 0xc04227e600, 0x0, 0x0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/operations.go:350 +0x998
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc0422be000, 0xc042268d80, 0x138b380, 0xc04227e100, 0xc0422be0d0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:377 +0x33b
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:406 +0xa6

    If I copy a file between bucket in the different region,it can copy the file ,but the contents of the document changed,and the size changed.The following is the contents of the file （Inside is the source bucket information）：
 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
  <Name>nishinamemei</Name>
  <Prefix></Prefix>
  <Marker></Marker>
  <MaxKeys>100</MaxKeys>
  <Delimiter></Delimiter>
  <IsTruncated>false</IsTruncated>
  <Contents>
<Key>hi/</Key>
<LastModified>2017-09-19T07:13:09.000Z</LastModified>
<ETag>"D41D8CD98F00B204E9800998ECF8427E"</ETag>
<Type>Normal</Type>
<Size>0</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
  <Contents>
<Key>notes.txt</Key>
<LastModified>2017-09-22T06:29:49.000Z</LastModified>
<ETag>"71057C4CB0A4227C912ED0FBE73877F5"</ETag>
<Type>Normal</Type>
<Size>1492</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
</ListBucketResult>

I do not know which method may be a problem，Can you give me some suggestions？

**Comment by luolibin** [comment]
Hello,I'm a newbee.I recently made a new remote to support a new cloud storage（The cloud storage is similar to s3, I imitate s3.go wrote the .go file）.But I met some problem with the copy method (mkdir,ls,lsd,rmdir and so on are good except for sync) .

     If I copy a file between bucket in the same region,it can't work，There is an error like this：

    C:\rclone>rclone copy oss:nishinamemei/notes.txt oss:luolibin321
    bucket:  nishinamemei
    directory:  notes.txt
    path:  nishinamemei/notes.txt
    endpoint:  xxxxxxx
    accessID: xxxxx
    accessKey:  xxxxx
    bucket:  luolibin321
    directory:
    path:  luolibin321
    endpoint:  oss-cn-hangzhou.aliyuncs.com
    accessID:  LTAIGvAl2UDOCPha
    accessKey:  FVZ0UOkBaXPhMDb2lqvhX6DdpiIaa0
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x58 pc=0x72ad68]

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x72ad68]

goroutine 46 [running]:
github.com/ncw/rclone/fs.Copy(0x138b380, 0xc04227e100, 0x0, 0x0, 0xc0422787a6, 0x9, 0x138b400, 0xc04227e600, 0x0, 0x0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/operations.go:350 +0x998
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc0422be000, 0xc042268d80, 0x138b380, 0xc04227e100, 0xc0422be0d0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:377 +0x33b
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:406 +0xa6

    If I copy a file between bucket in the different region,it can copy the file ,but the contents of the document changed,and the size changed.The following is the contents of the file （Inside is the source bucket information）：

 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
  <Name>nishinamemei</Name>
  <Prefix></Prefix>
  <Marker></Marker>
  <MaxKeys>100</MaxKeys>
  <Delimiter></Delimiter>
  <IsTruncated>false</IsTruncated>
  <Contents>
<Key>hi/</Key>
<LastModified>2017-09-19T07:13:09.000Z</LastModified>
<ETag>"D41D8CD98F00B204E9800998ECF8427E"</ETag>
<Type>Normal</Type>
<Size>0</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
  <Contents>
<Key>notes.txt</Key>
<LastModified>2017-09-22T06:29:49.000Z</LastModified>
<ETag>"71057C4CB0A4227C912ED0FBE73877F5"</ETag>
<Type>Normal</Type>
<Size>1492</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
</ListBucketResult>

I do not know which method may be a problem，Can you give me some suggestions？

**Comment by luolibin** [comment]
Hi,I met some problems.If I copy a file between bucket in the same region,it can't work，There is an error like this：

```
    C:\rclone>rclone copy oss:nishinamemei/notes.txt oss:luolibin321
    bucket:  nishinamemei
    directory:  notes.txt
    path:  nishinamemei/notes.txt
    endpoint:  xxxxxxx
    accessID: xxxxx
    accessKey:  xxxxx
    bucket:  luolibin321
    directory:
    path:  luolibin321
    endpoint:  oss-cn-hangzhou.aliyuncs.com
    accessID:  LTAIGvAl2UDOCPha
    accessKey:  FVZ0UOkBaXPhMDb2lqvhX6DdpiIaa0
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xc0000005 code=0x0 addr=0x58 pc=0x72ad68]

goroutine 46 [running]:
github.com/ncw/rclone/fs.Copy(0x138b380, 0xc04227e100, 0x0, 0x0, 0xc0422787a6, 0x9, 0x138b400, 0xc04227e600, 0x0, 0x0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/operations.go:350 +0x998
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopyOrMove(0xc0422be000, 0xc042268d80, 0x138b380, 0xc04227e100, 0xc0422be0d0)
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:377 +0x33b
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
        C:/GOPATH/src/github.com/ncw/rclone/fs/sync.go:406 +0xa6

```
If I copy a file between bucket in the different region,it can copy the file ,but the contents of the document changed,and the size changed.The following is the contents of the file （Inside is the source bucket information）：

```
 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult>
  <Name>nishinamemei</Name>
  <Prefix></Prefix>
  <Marker></Marker>
  <MaxKeys>100</MaxKeys>
  <Delimiter></Delimiter>
  <IsTruncated>false</IsTruncated>
  <Contents>
<Key>hi/</Key>
<LastModified>2017-09-19T07:13:09.000Z</LastModified>
<ETag>"D41D8CD98F00B204E9800998ECF8427E"</ETag>
<Type>Normal</Type>
<Size>0</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
  <Contents>
<Key>notes.txt</Key>
<LastModified>2017-09-22T06:29:49.000Z</LastModified>
<ETag>"71057C4CB0A4227C912ED0FBE73877F5"</ETag>
<Type>Normal</Type>
<Size>1492</Size>
<StorageClass>Standard</StorageClass>
<Owner>
  <ID>1118094827356724</ID>
  <DisplayName>1118094827356724</DisplayName>
</Owner>
  </Contents>
</ListBucketResult>

```
I do not know which method may be a problem，Can you give me some suggestions？

**Comment by luolibin** [comment]
@ @ncw I really need your help....Thank you very much.

**Comment by ncw** [comment]
@luolibin are you using the s3 remote code unmodified?  If not can you link to the source please?

Assuming you are using v1.37 then the traceback is at this line

```go
		err = errors.Errorf("corrupted on transfer: sizes differ %d vs %d", src.Size(), dst.Size())
```

Which would mean, most likely, that `dst` is `nil`.  Which most likely means that the `Copy` method in the fs returned a `nil` object without returning an error.

That is guesswork though, so if you could tell me what code (rclone version, or link to source) you are running that would help!

Thanks

**Comment by luolibin** [comment]
I was written according to oss-sdk，The rclone version is 1.37.
I can successfully use mkdir, rmdir, ls, lsd, size and other methods, and I can copy the local file upload to the cloud disk (although successful, but also read metadata fail and set modification time fail), but the copy method has a problem. I realized that you said the problem, I guess it will not be a problem with the readMetaData method in the .go file.
My English is not very good, may be a bit difficult to read, I hope you can understand .....

**Comment by luolibin** [comment]
@ncw I guess it  may be a problem with the readMetaData method in the .go file.I don't know if my guess is wrong.

**Comment by ncw** [comment]
I will sign up for an aliyun account and see if I can replicate the problem

This might be a place where Aliyun deviates slightly from AWS - hopefully we can find a work-around.

**Comment by luolibin** [comment]
Thank you very much.

**Comment by luolibin** [comment]
The problem has been solved，Thank you！

**Comment by ncw** [comment]
@luolibin 

I have finally managed to set up an Aliyun account so I'm ready to help now.

Do you have some code to share?

I haven't managed to make rclone work at all using the s3 interface - I keep getting

```
<Error>
  <Code>AccessDenied</Code>
  <Message>Anonymous access is forbidden for this operation.</Message>
  <RequestId>59E23342EABE051B37BDFA3F</RequestId>
  <HostId>oss-eu-central-1.aliyuncs.com</HostId>
</Error>
```

Which I don't understand as I'm sending an Authorization: header.

**Comment by luolibin** [comment]
Because the reasons for the time difference, so long to reply to you, I am sorry.
I was the first time to use golang, so the code is written messy, but now almost all functions can be achieved, but can not operate the bucket inside the folder directory.
Aliyun's sdk address: [https://github.com/aliyun/aliyun-oss-go-sdk/tree/master/oss]
Here is my code.
[oss.txt](https://github.com/ncw/rclone/files/1385116/oss.txt)

**Comment by luolibin** [comment]
And the Copy method in oss.go not executed when I copy something，and it can succeed.

**Comment by luolibin** [comment]
@ncw
I made a new file，it can operate the  the folder directory inside the bucket If I comment out this code（Line 651 in operations.go）：
```
// check remote name belongs in this directry
		remote := entry.Remote()
		switch {
		case !ok:
		 ignore
		case !strings.HasPrefix(remote, prefix):
			ok = false
			Errorf(entry, "Entry doesn't belong in directory %q (too short) - ignoring", dir)
		case remote == prefix:
			ok = false
			Errorf(entry, "Entry doesn't belong in directory %q (same as directory) - ignoring", dir)
		case strings.ContainsRune(remote[len(prefix):], '/'):
			ok = false
			Errorf(entry, "Entry doesn't belong in directory %q (contains subdir) - ignoring", dir)
		default:
		 ok
		}

```
Whether this will affect the use of other cloud disk？
[oss.txt](https://github.com/ncw/rclone/files/1386870/oss.txt)

**Comment by ncw** [comment]
Here is the first beta.  No docs yet!  The backend is called "oss" if anyone wants to try:

https://beta.rclone.org/branch/v1.45-094-g3d1958f4-oss-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've been round in circles with this backend, but eventually I remembered that Aliyun /Alibaba OSS works perfectly if you set the `force_path_style = false` config (See #2401).  All the integration tests work fine.

So what I've done is made config for OSS using the S3 backend and set the path style parameter automatically when the provider is set to `Alibaba`.

Thanks for @luolibin for the oss backend which we aren't using :-(

This will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and be released in v1.46
