### ISSUE TITLE
Cache not cleared automatically

### ISSUE THREAD

**Issue by easy90rider** [ncw/rclone#1857]
rclone -V
```
rclone v1.38-183-g02ffd435β
- os/arch: linux/amd64
- go version: go1.9.2
```

uname -a
`Ubuntu 16.04 VPS - Linux 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Chache mount settings: 

```
[cache]
type = cache
remote = mountPath:/
chunk_size = 5M
info_age = 1h
chunk_age = 1m
warmup_age = 3h
```

amazon -> cache -> encfs -> unionfuse -> emby
I suppose that using these settings I should get more HDD space after ~ 1 minute, right?

**Comment by ncw** [comment]
@remusb thoughts?

**Comment by easy90rider** [comment]
I can give logs...  is **-vv** enough?

I am not 100% sure how/when/why it happens...

**Comment by ncw** [comment]
Logs with `-vv` would be great - thanks

**Comment by easy90rider** [comment]
[rclone-cache-2017-11-24-12_03.txt](https://github.com/ncw/rclone/files/1502097/rclone-cache-2017-11-24-12_03.txt)
4.8MB!

Played a file in emby, then rescanned a library. After that I didn't do anything for a few hours.

Hope it helps. I see that in the end it crashed, this could have happened before, I don't know, my disk got 100% full. :( (I have around 10GB free)

**Comment by remusb** [comment]
It means something keeps fetching data from the cache and it never lets it expire. If you would hook up  your players directly to cache this might not happen.

This would also help: https://github.com/ncw/rclone/issues/1830
Cache in its current state is meant to work on a _cache everything that's needed_ manner. After that feature goes in it would be _cache X max size that's needed_

**Comment by easy90rider** [comment]
You mean not using unionfuse or encfs? How could I check who reads from the cache?

If you manage to solve #1830 then I will no longer have an issue :)

**Comment by remusb** [comment]
@easy90rider no, you should be able to use any combination of software you want that gets you the result you're after. It's just that a combination from the one you listed could result in that behaviour when cache isn't cleared anymore. It's just an artefact of how `cache` was build as a first iteration.

It does sound like #1830 will solve your issue since it will support continuous readings of the same chunks.

To validate, it's easy I think. I have `rclone` running on cache for over 2 weeks I think. Never saw it over 20GB (on a total library of 500GB). If you run it with `-v` you will see these types of messages in your log:

```
2017/11/16 17:46:09 INFO  : cache: running chunks cleanup
2017/11/16 17:46:09 INFO  : cache: deleted (414) chunks
2017/11/16 19:46:08 INFO  : cache: running chunks cleanup
2017/11/16 19:46:08 INFO  : cache: deleted (0) chunks
2017/11/16 21:46:09 INFO  : cache: running chunks cleanup
2017/11/16 21:46:09 INFO  : cache: deleted (0) chunks
2017/11/16 21:59:29 INFO  : cache: running root cleanup
2017/11/16 21:59:29 INFO  : cache: deleted (69) entries
2017/11/16 22:46:32 INFO  : cache:enc: turning on cache warmup
2017/11/16 23:14:07 INFO  : cache:enc: turning off cache warmup
2017/11/16 23:16:34 INFO  : cache: running chunks cleanup
2017/11/16 23:16:34 INFO  : cache: deleted (31) chunks
2017/11/17 00:59:37 INFO  : cache: running chunks cleanup
2017/11/17 00:59:37 INFO  : cache: deleted (0) chunks
```

`cache: deleted (31) chunks` is key here. It means the cron cleanup works and is cleaning up old data. If it's always 0 then it means that is constantly being read and not allowed to be evicted. If you don't see these messages at all then it could be a bug and in that case I would ask you for more verbose logs or more details on the setup :)

**Comment by remusb** [comment]
@easy90rider 
I have a PR open https://github.com/ncw/rclone/pull/1884 that needs to go in and after that I'll make a push to a couple of `cache` changes that should help with your issue too.

Cleanup will be performed based on disk usage now, not expire after some time. I'll ping back here once a beta is ready.

Thanks

**Comment by easy90rider** [comment]
@remusb looking forward to the updated beta!

**Comment by remusb** [comment]
https://beta.rclone.org/v1.38-217-gb48b5373/

Here's the latest beta I mentioned. Since you're using Plex, it would be great if you use the integration and configure rclone to talk with Plex to manage load during scans and playback. You can also configure a max cache size so you shouldn't max out the disk space anymore.

It's in the doc: https://github.com/ncw/rclone/blob/master/docs/content/cache.md

**Comment by easy90rider** [comment]
Can I see in the logs if I configured plex ok?

BTW I am also using emby.

**Comment by easy90rider** [comment]
@remusb 
I downloaded a file, at around 9:48, to fill up the cache, after that I scanned a library in plex and I got this error:

```
2017/12/10 10:01:24 INFO  : cache: deleted (0) chunks
2017/12/10 10:02:24 INFO  : cache: deleted (34) chunks
2017/12/10 10:03:25 INFO  : cache: deleted (67) chunks
panic: runtime error: slice bounds out of range

goroutine 171148 [running]:
github.com/ncw/rclone/cache.(*Handle).getChunk(0xc427c7f730, 0x6e00000, 0xc427c7f768, 0xc42b706600, 0x429909, 0xc42005a5d0, 0xc42b706620)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:235 +0x524
github.com/ncw/rclone/cache.(*Handle).Read(0xc427c7f730, 0xc4285aa000, 0x1000, 0x100000, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cache/handle.go:257 +0xd4
github.com/ncw/rclone/fs.ReadFill(0x7f5d201b5db8, 0xc427c7f730, 0xc4285aa000, 0x1000, 0x100000, 0xe6ef20, 0xf3cc40, 0xeb0f00)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/operations.go:918 +0x72
github.com/ncw/rclone/fs.(*buffer).read(0xc429fdfa10, 0x7f5d201b5db8, 0xc427c7f730, 0x7f5d201b5db8, 0xc427c7f730)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:255 +0x58
github.com/ncw/rclone/fs.(*asyncReader).init.func1(0xc427c7f960)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:85 +0x1e4
created by github.com/ncw/rclone/fs.(*asyncReader).init
        /home/travis/gopath/src/github.com/ncw/rclone/fs/buffer.go:73 +0x1ab
```

[cache]
type = cache
remote = google:/
chunk_size = 5M
info_age = 12h
chunk_age = 60s
warmup_age = 3h
plex_url = http://127.0.0.1:32400
plex_username = user
plex_password = *** ENCRYPTED ***
chunk_total_size = 5G
plex_token = TOKEN

rclone v1.38-217-gb48b5373β
- os/arch: linux/amd64
- go version: go1.9.2

**Comment by remusb** [comment]
1 minute is fine. it's not removing files in 1 minute, it's just the interval at which cleanup should run as a best effort (it will not run at all if there is no activity).

Files will stay in cache until the total cache size is reached and the oldest will be removed every minute. 

It is in no way the duration for a file to stay in cache.

**Comment by easy90rider** [comment]
Oh, I see! The rest seems to be related to: #1896 , right? If so, I think my issue can be closed, since there is a solution for it.

**Comment by remusb** [comment]
Yes, check the issue, I'm already catching that panic and added additional logging to understand where the issue comes from. Those error reports will really help me.

**Comment by remusb** [comment]
closing this as it is no longer an issue after https://github.com/ncw/rclone/issues/1830
the panic was also fixed under https://github.com/ncw/rclone/issues/1896
