### ISSUE TITLE
Error after finish sync with cached crypt mount

### ISSUE THREAD

**Issue by vampywiz17** [ncw/rclone#1961]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu Server 17.10

> Which cloud storage system are you using? (eg Google Drive)

Google Drive->Cache->Crypt

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```

2018/01/06 14:40:02 INFO  : cache: Cache DB path: /root/.cache/rclone/cache-backend/cache.db
2018/01/06 14:40:02 INFO  : cache: Cache chunk path: /root/.cache/rclone/cache-backend/cache
2018/01/06 14:40:02 INFO  : cache: Chunk Memory: true
2018/01/06 14:40:02 INFO  : cache: Chunk Size: 5M
2018/01/06 14:40:02 INFO  : cache: Chunk Total Size: 10G
2018/01/06 14:40:02 INFO  : cache: Chunk Clean Interval: 1m0s
2018/01/06 14:40:02 INFO  : cache: Workers: 4
2018/01/06 14:40:02 INFO  : cache: File Age: 24h0m0s
2018/01/06 14:40:02 INFO  : cache: Cache Writes: false
2018/01/06 14:40:02 INFO  : cache: deleted (0) chunks
2018/01/06 14:40:03 INFO  : cache: Cache DB path: /root/.cache/rclone/cache-backend/cache.db
2018/01/06 14:40:03 INFO  : cache: Cache chunk path: /root/.cache/rclone/cache-backend/cache
2018/01/06 14:40:03 INFO  : cache: Chunk Memory: true
2018/01/06 14:40:03 INFO  : cache: Chunk Size: 5M
2018/01/06 14:40:03 INFO  : cache: Chunk Total Size: 10G
2018/01/06 14:40:03 INFO  : cache: Chunk Clean Interval: 1m0s
2018/01/06 14:40:03 INFO  : cache: Workers: 4
2018/01/06 14:40:03 INFO  : cache: File Age: 24h0m0s
2018/01/06 14:40:03 INFO  : cache: Cache Writes: false
2018/01/06 14:40:03 INFO  : Encrypted drive 'Google_gsuite_crypt:temp': Modify window is 1ms
panic: runtime error: slice bounds out of range

goroutine 56 [running]:
github.com/ncw/rclone/cache.(*Directory).Remote(0xc420078540, 0x67, 0x67)
        /home/ncw/go/src/github.com/ncw/rclone/cache/directory.go:98 +0x117
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries.func1(0xc42037e8c0, 0xff02f8, 0xc42037e8c0)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc4200ac3c0, 0xc42045fb68, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:680 +0x9a
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries(0xc42023e190, 0xc420078540, 0x0, 0xc420078540, 0x8, 0x10, 0xc420336fb0)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/cache.(*Fs).List(0xc4201000d0, 0x0, 0x0, 0x0, 0x0, 0xc4203f2f6f, 0xa, 0x28)
        /home/ncw/go/src/github.com/ncw/rclone/cache/cache.go:461 +0xb3
github.com/ncw/rclone/crypt.(*Fs).List(0xc420206640, 0x0, 0x0, 0x1, 0xa1ff, 0x0, 0x0, 0x28)
        /home/ncw/go/src/github.com/ncw/rclone/crypt/crypt.go:236 +0x76
github.com/ncw/rclone/fs.ListDirSorted(0x158bae0, 0xc420206640, 0x429800, 0x0, 0x0, 0x801, 0x75da83, 0xc4203f7730, 0xc4203f7738, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.(*march).makeListDir.func1(0x0, 0x0, 0xc42035efd0, 0x25a20c1a, 0x59d3143a, 0x37a19ed3, 0x59d3143a)
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:70 +0x53
github.com/ncw/rclone/fs.(*march).processJob.func2(0xc42035efd0, 0xc42031fb20, 0xc420336fa0, 0xc4200e2e80, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, ...)
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:337 +0x72
created by github.com/ncw/rclone/fs.(*march).processJob
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:335 +0xe46


```

If I sync something Local to Google->Cache->Crypt, after it finished (without any error, by the way...) i get the above error in log.

**Comment by ncw** [comment]
@remusb ?

**Comment by vampywiz17** [comment]
Now i try the cryptcheck and not working. I get this:


```
2018/01/06 18:52:04 INFO  : cache: Cache DB path: /home/vamp/.cache/rclone/cache-backend/cache.db
2018/01/06 18:52:04 INFO  : cache: Cache chunk path: /home/vamp/.cache/rclone/cache-backend/cache
2018/01/06 18:52:04 INFO  : cache: Chunk Memory: true
2018/01/06 18:52:04 INFO  : cache: Chunk Size: 5M
2018/01/06 18:52:04 INFO  : cache: Chunk Total Size: 10G
2018/01/06 18:52:04 INFO  : cache: Chunk Clean Interval: 1m0s
2018/01/06 18:52:04 INFO  : cache: Workers: 4
2018/01/06 18:52:04 INFO  : cache: File Age: 24h0m0s
2018/01/06 18:52:04 INFO  : cache: Cache Writes: false
2018/01/06 18:52:04 INFO  : cache: deleted (0) chunks
2018/01/06 18:52:05 INFO  : cache: Cache DB path: /home/vamp/.cache/rclone/cache-backend/cache.db
2018/01/06 18:52:05 INFO  : cache: Cache chunk path: /home/vamp/.cache/rclone/cache-backend/cache
2018/01/06 18:52:05 INFO  : cache: Chunk Memory: true
2018/01/06 18:52:05 INFO  : cache: Chunk Size: 5M
2018/01/06 18:52:05 INFO  : cache: Chunk Total Size: 10G
2018/01/06 18:52:05 INFO  : cache: Chunk Clean Interval: 1m0s
2018/01/06 18:52:05 INFO  : cache: Workers: 4
2018/01/06 18:52:05 INFO  : cache: File Age: 24h0m0s
2018/01/06 18:52:05 INFO  : cache: Cache Writes: false
2018/01/06 18:52:05 INFO  : Encrypted drive 'Google_gsuite_crypt:temp': Modify window is 1ms
2018/01/06 18:52:05 INFO  : Using MD5 for hash comparisons
2018/01/06 18:52:05 INFO  : Encrypted drive 'Google_gsuite_crypt:temp': Waiting for checks to finish
panic: runtime error: slice bounds out of range
goroutine 49 [running]:
github.com/ncw/rclone/cache.(*Directory).Remote(0xc420108850, 0x4d, 0x4d)
        /home/ncw/go/src/github.com/ncw/rclone/cache/directory.go:98 +0x117
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries.func1(0xc4212e36c0, 0xff02f8, 0xc4212e36c0)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc42014a3c0, 0xc4203ecb68, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:680 +0x9a
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries(0xc420290640, 0xc420108850, 0x0, 0xc420108850, 0x8, 0x10, 0xc420343d80)
        /home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/cache.(*Fs).List(0xc42042f520, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/cache/cache.go:461 +0xb3
github.com/ncw/rclone/crypt.(*Fs).List(0xc4213f5090, 0x0, 0x0, 0xc4212e0d00, 0x4e1090, 0xc4212e0d20, 0x4e1090, 0xc4212e0d40)
        /home/ncw/go/src/github.com/ncw/rclone/crypt/crypt.go:236 +0x76
github.com/ncw/rclone/fs.ListDirSorted(0x158bae0, 0xc4213f5090, 0x429800, 0x0, 0x0, 0x0, 0x75da83, 0xc4212d5730, 0xc4212d5738, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/fs.(*march).makeListDir.func1(0x0, 0x0, 0xc420321550, 0x8, 0x0, 0x0, 0x0)
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:70 +0x53
github.com/ncw/rclone/fs.(*march).processJob.func2(0xc420321550, 0xc420318b80, 0xc420343d70, 0xc42017ef80, 0x0, 0x0, 0x0, 0x0, 0x7ffffffe, 0x7ffffffe, ...)
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:337 +0x72
created by github.com/ncw/rclone/fs.(*march).processJob
        /home/ncw/go/src/github.com/ncw/rclone/fs/march.go:335 +0xe46
```

**Comment by vampywiz17** [comment]
**Update:** I tried the cryptocheck without cache and working normal.

**Comment by remusb** [comment]
This was fixed and can be found in the latest beta: https://beta.rclone.org

https://github.com/ncw/rclone/commit/29d428040cccbead2d40a47da47aece8cf55a94f
