### ISSUE TITLE
mounting gdrive cache panics

### ISSUE THREAD

**Issue by jbreitbart** [ncw/rclone#1974]
I was just trying to configure a cache for my gdrive mount, but it I cannot access the directory after mounting. `ls` returns `ls: reading directory <path>': Input/output error`. `rclone` itself returns

```
$ rclone mount  gdrive-cache:/ <path>
2018/01/14 11:44:09 NOTICE: gdrive-cache:/: poll-interval is not supported by this remote
2018/01/14 11:44:17 fuse: panic in handler for Read [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=2906] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock: runtime error: slice bounds out of range
goroutine 24 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x15853a0, 0xc4204cc0e0, 0xc420125ef8, 0xc420125e6f)
	/home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1b1
panic(0xe5ff40, 0x15cddc0)
	/opt/go/go1.9/src/runtime/panic.go:491 +0x283
github.com/ncw/rclone/cache.(*Directory).Remote(0xc420090b60, 0x9, 0x9)
	/home/ncw/go/src/github.com/ncw/rclone/cache/directory.go:98 +0x117
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries.func1(0xc4202fb960, 0xff02f8, 0xc4202fb960)
	/home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:204 +0x2d5
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).View(0xc4201463c0, 0xc420487478, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:680 +0x9a
github.com/ncw/rclone/cache.(*Persistent).GetDirEntries(0xc42026e820, 0xc420090b60, 0x0, 0xc420090b60, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/cache/storage_persistent.go:182 +0x7d
github.com/ncw/rclone/cache.(*Fs).List(0xc42007d520, 0x0, 0x0, 0xc42014d658, 0x0, 0xc4201fb720, 0x45b236, 0x1e4)
	/home/ncw/go/src/github.com/ncw/rclone/cache/cache.go:461 +0xb3
github.com/ncw/rclone/fs.ListDirSorted(0x158b9e0, 0xc42007d520, 0x15eac00, 0x0, 0x0, 0x4, 0x1, 0xc42044ed90, 0x5, 0xc4201fb810)
	/home/ncw/go/src/github.com/ncw/rclone/fs/operations.go:629 +0x63
github.com/ncw/rclone/vfs.(*Dir)._readDir(0xc420262000, 0xff1700, 0xc420262060)
	/home/ncw/go/src/github.com/ncw/rclone/vfs/dir.go:182 +0x112
github.com/ncw/rclone/vfs.(*Dir).ReadDirAll(0xc420262000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/vfs/dir.go:301 +0xc2
github.com/ncw/rclone/cmd/mount.(*Dir).ReadDirAll(0xc4201fe010, 0x1587060, 0xc42014d6c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/go/src/github.com/ncw/rclone/cmd/mount/dir.go:91 +0x1c4
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc420264180, 0x1587060, 0xc42014d6c0, 0x157b820, 0xc4201fe010, 0xc4202a0340, 0x15853a0, 0xc4204cc0e0, 0xc420125ef8, 0x0, ...)
	/home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1209 +0x3fe
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc420264180, 0x15853a0, 0xc4204cc0e0)
	/home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x468
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc420264180, 0x15853a0, 0xc4204cc0e0)
	/home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
	/home/ncw/go/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:423 +0x35f
```

I am running version
```
$ rclone version
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2
```

Mounting the remote directly works fine.

**Comment by HeroCC** [comment]
Same issue here, Google Drive -> Cache -> Crypt. My remote mount no longer works, and I can't use rclone commands at the same time as the mount because of this: 
```
$ rclone lsd SGDMedia:
2018/01/15 00:52:42 ERROR : /home/herocc/.cache/rclone/cache-backend/SGDCache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/herocc/.cache/rclone/cache-backend/SGDCache.db": timeout
2018/01/15 00:52:43 ERROR : /home/herocc/.cache/rclone/cache-backend/SGDCache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/herocc/.cache/rclone/cache-backend/SGDCache.db": timeout
2018/01/15 00:52:43 Failed to create file system for "SGDMedia:": failed to make remote "SGDCache:/media" to wrap: failed to start cache db: failed to open a cache connection to "/home/herocc/.cache/rclone/cache-backend/SGDCache.db": timeout
```

**Comment by jackusm** [comment]
Try mounting with rclone mount  gdrive-cache: <path> instead (no root /). Not sure what's causing the errors with that but I had them and that worked for me.

**Comment by HeroCC** [comment]
@jackusm that fixed it, thanks! I removed the front / from all of my configs and that fixed it

**Comment by jbreitbart** [comment]
Thanks, that seems to fix the issue. I keep the issue open as I am not sure if this is intended behavior. @ncw (or any other maintainer) feel free to close this issue if that intended behavior.

**Comment by HeroCC** [comment]
Looks like this is a bug: #1945

**Comment by ncw** [comment]
Yes #1945 is the bug.  There is a fix in the pipeline for it too :-)

I'll close this one.

**Comment by dual-oo** [comment]
I have this issue too.
But I have no / in remote

my config GD > cache > crypt > mount
