### ISSUE TITLE
Sporalic Rclone Panic invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tabacha** [ncw/rclone#2160]
#### What is the problem you are having with rclone?

Sporalic (once a week) rclone panic.

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.39-120-g82418c30β
- os/arch: freebsd/amd64
- go version: go1.9.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Freenas

####  Which cloud storage system are you using? (eg Google Drive)

Backblaze Encrypted

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
LOG=/root/log/rclone`date +%Y-%m-%d-%H%M%S`.log
DATUM=`date +%Y%m%d`
DESTDIR=`ls -tda /mnt/backup/.zfs/snapshot/auto-$DATUM*2w | head -1`
cd /root
rm -f rclone.log
touch $LOG
ln -s $LOG rclone.log
WHAT="/"
# WHAT="ron/"
./rclone-v1.39-120-g82418c30?-freebsd-amd64/rclone sync -v --transfers 10 \
  --log-file=$LOG\
  --fast-list\
  --filter-from /root/rclone-filter.txt\
  --bwlimit 1M --skip-links $DESTDIR$WHAT crypt:$WHAT
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

(sorry it is not -vv, only -v)

```
2018/03/21 03:00:15 INFO  : dumbledore/var/lib/unifi/db/journal/lsn: Copied (replaced existing)
2018/03/21 03:00:16 NOTICE: gandalf/etc.20170927/runit/univention-directory-listener/supervise/ok: Can't transfer non file/directory
2018/03/21 03:00:16 NOTICE: gandalf/etc.20170927/runit/univention-directory-listener/supervise/control: Can't transfer non file/directory
2018/03/21 03:00:17 NOTICE: gandalf/etc.20170927/runit/univention-directory-notifier/supervise/ok: Can't transfer non file/directory
2018/03/21 03:00:17 NOTICE: gandalf/etc.20170927/runit/univention-directory-notifier/supervise/control: Can't transfer non file/directory
2018/03/21 03:00:18 INFO  : ron/etc/univention/base-ldap.conf: Copied (replaced existing)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa3c467]

goroutine 368442 [running]:
github.com/ncw/rclone/backend/local.(*localOpenFile).Read(0xc4ca6a81e0, 0xc4b762a000, 0x10000, 0x10010, 0xc4e11af748, 0xc420018000, 0xc4778d9e00)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/local/local.go:661 +0x47
io.ReadAtLeast(0x804d61380, 0xc4ca6a81e0, 0xc4b762a000, 0x10000, 0x10010, 0x10000, 0xc4e11af7c0, 0xc4e11af7c8, 0x43d6c4)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:309 +0x86
io.ReadFull(0x804d61380, 0xc4ca6a81e0, 0xc4b762a000, 0x10000, 0x10010, 0x73de3d, 0x162b6c0, 0x15a8460)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:327 +0x58
github.com/ncw/rclone/backend/crypt.(*encrypter).Read(0xc4c59ca120, 0xc48a54b28c, 0x28, 0xd74, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/cipher.go:658 +0xfd
github.com/ncw/rclone/fs/accounting.(*Account).read(0xc42aaf1080, 0x159c7e0, 0xc4c59ca120, 0xc48a54b28c, 0x28, 0xd74, 0x12, 0xc48a54b23a, 0xc4c59cc554)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/accounting/accounting.go:141 +0x107
github.com/ncw/rclone/fs/accounting.(*accountStream).Read(0xc46bd95160, 0xc48a54b28c, 0x28, 0xd74, 0x72, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/accounting/accounting.go:317 +0x5e
io.(*teeReader).Read(0xc46bd951a0, 0xc48a54b28c, 0x28, 0xd74, 0x72, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:525 +0x55
github.com/ncw/rclone/backend/b2.(*hashAppendingReader).Read(0xc427433380, 0xc48a54b28c, 0x28, 0xd74, 0x72, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/b2/upload.go:36 +0x7f
io/ioutil.(*nopCloser).Read(0xc43079f790, 0xc48a54b28c, 0x28, 0xd74, 0x72, 0x0, 0x0)
        <autogenerated>:1 +0x5a
net/http.transferBodyReader.Read(0xc4ebd888c0, 0xc48a54b28c, 0x28, 0xd74, 0x72, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/net/http/transfer.go:60 +0x56
io.(*LimitedReader).Read(0xc46bd95200, 0xc48a54b28c, 0xd74, 0xd74, 0x72, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:438 +0x63
bufio.(*Writer).ReadFrom(0xc499ddf780, 0x159dea0, 0xc46bd95200, 0x8017abd40, 0xc499ddf780, 0x1)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/bufio/bufio.go:697 +0xcd
io.copyBuffer(0x159bfe0, 0xc499ddf780, 0x159dea0, 0xc46bd95200, 0x0, 0x0, 0x0, 0xeb5520, 0xfb8201, 0xc46bd95200)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:386 +0x2bb
io.Copy(0x159bfe0, 0xc499ddf780, 0x159dea0, 0xc46bd95200, 0x1, 0x517c3d, 0xc48a54b1f8)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/io/io.go:362 +0x68
net/http.(*transferWriter).WriteBody(0xc4ebd888c0, 0x159bfe0, 0xc499ddf780, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/net/http/transfer.go:337 +0x62c
net/http.(*Request).write(0xc432559e00, 0x159bfe0, 0xc499ddf780, 0x0, 0xc4ca6a83f0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/net/http/request.go:618 +0x6eb
net/http.(*persistConn).writeLoop(0xc4fb84e7e0)
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/net/http/transport.go:1762 +0x201
created by net/http.(*Transport).dialConn
        /home/travis/.gimme/versions/go1.9.3.linux.amd64/src/net/http/transport.go:1187 +0xa53
```

**Comment by ncw** [comment]
This has already been fixed in 7d4da1c66ad434d85452b311f6acd36ca8727037

You can find this in [the latest beta](https://beta.rclone.org) or the [1.41 release](https://rclone.org/downloads/) :-)
