### ISSUE TITLE
Stats to terminal while logging to file

### ISSUE THREAD

**Issue by SL-Gundam** [ncw/rclone#2501]
This is a feature request

#### What is the problem you are having with rclone?
I would like Rclone to support the following
Output stats to console/terminal while "log to file" is active. Stats should not be outputted to the "log to file"
Is it possible that an extra parameter is added so that we can decide where the stats should be outputted (to log or to console/terminal)
The summary stats at the end should still be logged to file

#### What is your rclone version (eg output from `rclone -V`)
1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 x64 1803

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone.exe sync --delete-after --bwlimit 3M --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --stats 1s --log-file "C:\Log\Rclone.log" --log-level INFO D:/ cryptGDrive:D

**Comment by ncw** [comment]
I think you are probably looking for the `--progress` or `-P` flag in [the latest beta](https://beta.rclone.org).

This will output updating stats to the terminal and you can send the log elsewhere with --log-file.

**Comment by SL-Gundam** [comment]
The latest beta results in this for me so i was unable to test it
C:\rclone\rclone.exe sync --delete-after --bwlimit 3M --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --progress --stats 0m --log-file "Rclone Mirror_D 2018-09-01  43037-Simulate.log" --log-level DEBUG --dry-run D:/ cryptGDrive:D


2018/09/01 04:30:38 DEBUG : rclone: Version "v1.42-157-gb4d86d54" starting with parameters ["C:\\rclone\\rclone.exe" "sync" "--delete-after" "--bwlimit" "3M" "--delete-excluded" "--exclude-from" "C:/rclone/Configs/Exclusions.txt" "--progress" "--stats" "0m" "--log-file" "Rclone Mirror_D 2018-09-01  43037-Simulate.log" "--log-level" "DEBUG" "--dry-run" "D:/" "cryptGDrive:D"]
2018/09/01 04:30:38 DEBUG : Using config file from "C:\\Users\\Username\\.config\\rclone\\rclone.conf"
2018/09/01 04:30:38 INFO  : Starting bandwidth limiter at 3MBytes/s
panic: non-positive interval for NewTicker

goroutine 25 [running]:
time.NewTicker(0x0, 0xc0003a3f58)
	C:/go/src/time/tick.go:23 +0x196
github.com/ncw/rclone/cmd.startProgress.func2(0xc00006c300, 0x11c2bc0)
	C:/gopath/src/github.com/ncw/rclone/cmd/progress.go:44 +0x58
created by github.com/ncw/rclone/cmd.startProgress
	C:/gopath/src/github.com/ncw/rclone/cmd/progress.go:39 +0x89

**Comment by ncw** [comment]
Remove the "--stats 0m" and it will work.  I'll fix that now!

**Comment by ncw** [comment]
I've fixed that in [the latest beta](https://beta.rclone.org) (uploaded in 15-30 mins).

Note that 1.43 is released which should work provided you don't use `--progress` and `--stats 0` together!

**Comment by SL-Gundam** [comment]
Thank you
Works perfectly

**Comment by SL-Gundam** [comment]
I've found an issue

When --progress is enabled i sometimes get a lot of these errors in the console.

`*** Error from ANSI parser: New state of 'nil' is invalid.`

After some investigation the following filename wil trigger this. These are chinese characters. Japanese and Korean characters don't seem to be an issue though

> 狐妖小红娘.ext

Test command
`C:\rclone\rclone.exe sync --delete-after --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --progress --log-file "C:\Users\username\Desktop\Rclone TEST.log" --log-level DEBUG E:/test/ cryptGDrive:TEST`

**Comment by SL-Gundam** [comment]
no i don't see them.

Japanese and korean characters are not shown and do not generate errors.
Chinese characters generate the beforementioned error

Personally i don't really care that the utf8 characters are not shown, just as long as the error is suppressed since that actually blocks showing "--progress"

**Comment by ncw** [comment]
@SL-Gundam thanks for the clarification.

The best way forward on this would be to fix the above issue - fancy having a look at that?

I think a reasonable fix for you would be not to report errors from the parser which would at least make `-P` useful.  What do you think of that?

**Comment by SL-Gundam** [comment]
In this specific situation the ANSI parser error is useless in my opinion.
I'm not sure what other situations it might occur and might actually be wanted

So suppressing the error would be fine for me. Another option is to move the error to log level DEBUG. Since debug is used to test mostly, production environments would not affected

**Comment by ncw** [comment]
I supressed the error here.

Can you have a go with it?  Does the ansiparser display something sensible even though there was an error?

https://beta.rclone.org/branch/v1.43-075-ge367b399-fix-2501-progress-errors-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by SL-Gundam** [comment]
I'm sorry to say but its not fixed.
The error is not shown. Thats good. But the progress is also not shown as can be seen from the screenshot

Rclone 1.43-075
![image](https://user-images.githubusercontent.com/912973/45571254-f23b9980-b865-11e8-920e-eabf529cb8d8.png)

Rclone 1.43.1:
![image](https://user-images.githubusercontent.com/912973/45571355-3a5abc00-b866-11e8-9105-a0b93b807a72.png)

**Comment by ncw** [comment]
OK I had another idea - here I just replace all non-ASCII characters with `.`

I think that should fix the strange behaviour - it isn't ideal but hopefully will do until the upstream bug is fixed.

https://beta.rclone.org/branch/v1.43-137-g60dac68f-fix-2501-progress-errors-beta/ (uploaded in 15-30 mins)

What do you think of that @SL-Gundam ?

**Comment by SL-Gundam** [comment]
For "v1.43-137-g60dac68f-fix-2501-progress-errors-beta" the windows version is still not available so i tested against "v1.43-139-g87ef3cc6-fix-2438-s3-v2-sign-beta"
Not sure whether this change is present in that version

To my knowledge its not an issue for the command prompt if you output UTF8. I will just show a question mark since the font being used does not support UTF8 characters (based on my experience with robocopy). It should suffice to make sure that Rclone's ANSI Parser does not stumble on the UTF8 characters.

See the result below. I'm afraid its unchanged

![image](https://user-images.githubusercontent.com/912973/46686724-52b9be80-cbf9-11e8-93a3-763d08de3e16.png)

**Comment by ncw** [comment]
@SL-Gundam 

The windows build bot decided to take a holiday!

Try this one instead

https://beta.rclone.org/branch/v1.43-138-gf6c174e9-fix-2501-progress-errors-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by SL-Gundam** [comment]
Works perfectly :thumbsup:

![image](https://user-images.githubusercontent.com/912973/46822374-9d6b4000-cd8b-11e8-8947-4e6a8b071ab9.png)
