### ISSUE TITLE
Running `info` on the parent of a crypt remote breaks the crypted remote

### ISSUE THREAD

**Issue by Saviq** [ncw/rclone#2826]
#### What is the problem you are having with rclone?
I ran `rclone info` on a `drive` remote. Subsequently I could not use the `crypt` remote over it any more. The `info` command seems to have sent a bunch of files:

```plain
$ rclone ls --drive-trashed-only Drive:
       50 0x01--
       50 0x02--
       50 0x03--
       50 0x05--
       50 0x06--
       50 0x07--
…
       50 Héroique
       50 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
       32 checkStreamingTest
```

This then results in a panic when trying to list that directory through `crypt`:

```plain
$ rclone ls --drive-trashed-only CryptedDrive:
2018/12/09 10:55:39 EME operates on 1 to 128 block-cipher blocks, you passed 300
panic: EME operates on 1 to 128 block-cipher blocks, you passed 300

goroutine 21 [running]:
log.Panicf(0x111eda7, 0x3a, 0xc0004ffa60, 0x2, 0x2)
        /home/travis/.gimme/versions/go1.11.linux.amd64/src/log/log.go:333 +0xda
github.com/ncw/rclone/vendor/github.com/rfjakob/eme.Transform(0x1265ea0, 0xc000082630, 0xc00033acc0, 0x10, 0x10, 0xc001400000, 0x12c0, 0x12c0, 0xc000482000, 0x1e00, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/rfjakob/eme/eme.go:128 +0x125
github.com/ncw/rclone/backend/crypt.(*cipher).decryptSegment(0xc00033ac80, 0xc000482000, 0x1e00, 0x1, 0xc00022dff0, 0x1, 0x1)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/cipher.go:289 +0xdd
github.com/ncw/rclone/backend/crypt.(*cipher).decryptFileName(0xc00033ac80, 0xc000482000, 0x1e00, 0x409a18, 0x10, 0xeeac00, 0xc00000b401)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/cipher.go:520 +0xd0
github.com/ncw/rclone/backend/crypt.(*cipher).DecryptFileName(0xc00033ac80, 0xc000482000, 0x1e00, 0x24, 0xc0004ffc80, 0x1, 0x408bfb)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/cipher.go:541 +0xf9
github.com/ncw/rclone/backend/crypt.(*Fs).add(0xc0000a8500, 0xc0004ffd38, 0x1272920, 0xc000298500)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/crypt.go:223 +0x7d
github.com/ncw/rclone/backend/crypt.(*Fs).encryptEntries(0xc0000a8500, 0xc000348000, 0x8c, 0x100, 0xc000348000, 0x0, 0x100, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/crypt.go:254 +0x102
github.com/ncw/rclone/backend/crypt.(*Fs).List(0xc0000a8500, 0x0, 0x0, 0x0, 0x0, 0xc000055f20, 0xc00002e100, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/crypt.go:278 +0xe2
github.com/ncw/rclone/fs/list.DirSorted(0x12727a0, 0xc0000a8500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/fs/walk.walk.func2(0xc000039270, 0xc000078900, 0x1144dd8, 0x12727a0, 0xc0000a8500, 0xc0013a3a00, 0xc0000392a0, 0xc00028e0d0, 0xc000039280, 0xc00015b830, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:122 +0x1b7
created by github.com/ncw/rclone/fs/walk.walk
        /home/travis/gopath/src/github.com/ncw/rclone/fs/walk/walk.go:114 +0x252
```

#### What is your rclone version (output from `rclone version`)
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsd crypted-remote:`

**Comment by ncw** [comment]
The problem with this is that `rclone info` has made a file that is too long for crypt to deal with!

Crypt shouldn't panic here!

If you want to remove the file then you'll have to do it with the underlying remote or the web interface.

Note that `rclone info` is a hidden command for testing purposes and quite often makes files you can't remove with rclone!

**Comment by garrmcnu** [comment]
The EME Transform() method will panic if the decoded filename is larger than 2048 bytes. It is possible for the user to create a file with a name that is too long be decrypted (e.g. using the web interface of the underlying remote).
Adding an additional check on the length causes these files to be skipped.

**Comment by ncw** [comment]
Thank you @garrmcnu for the fix :-)
