### ISSUE TITLE
Crash during upload to crypt over webdav

### ISSUE THREAD

**Issue by comio** [ncw/rclone#2963]
Hi,
Thanks for your tool. I will use everyday. Today I received the following crash.

#### What is the problem you are having with rclone?
Crash on rclone copy  from directory to crypt over webdav.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
`Linux gentoobox 4.20.7-gentoo #1 SMP Thu Feb 7 10:45:06 CET 2019 x86_64 Intel(R) Pentium(R) CPU N3700 @ 1.60GHz GenuineIntel GNU/Linux`

####  Which cloud storage system are you using? (eg Google Drive)
Crypt over Webdav

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy --checksum --progress --bwlimit "06:30,2M 08:00,1M 11:00,2M 13:00,512K 14:00,2M 18:00,1M 00:00,3M /my/dir webdav_crypt:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Uploading directory mydir/...
2019-02-10 03:14:47 NOTICE: Scheduled bandwidth change. Limit set to 3MBytes/s
Transferred:      268.969M / 3.904 GBytes, 7%, 2.750 MBytes/s, ETA 22m35s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 10, 10%
Elapsed time:     1m37.8s
Transferring:
 * file1.txt:  0% /314.673M, 916/s, 99h28m19s
 * file2.txt:  0% /447.568M, 608/s, 213h50m24s
 * file3.txt:  0% /480.139M, 401/s, 348h2m23s
 * file4.txt: 57% /460.521M, 2.889M/s, 1m7spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe0af46]

goroutine 69 [running]:
github.com/ncw/rclone/backend/webdav.shouldRetry(0x0, 0x141c700, 0xc0001446f0, 0x0, 0xfea500, 0xc004c28160)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:160 +0x26
github.com/ncw/rclone/backend/webdav.(*Fs).readMetaDataForPath.func1(0xc0002b2690, 0x40dc9f, 0xc00041b020)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:204 +0xb8
github.com/ncw/rclone/lib/pacer.(*Pacer).call(0xc0002b2690, 0xc00041b020, 0xa, 0x11c9e60, 0x1211f01)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/lib/pacer/pacer.go:405 +0x16a
github.com/ncw/rclone/lib/pacer.(*Pacer).Call(0xc0002b2690, 0xc00041b020, 0x127187e, 0x5)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/lib/pacer/pacer.go:428 +0x66
github.com/ncw/rclone/backend/webdav.(*Fs).readMetaDataForPath(0xc00038a790, 0xc00030e7e0, 0x82, 0x126ff38, 0x1, 0x1, 0x0, 0x0)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:202 +0x274
github.com/ncw/rclone/backend/webdav.(*Object).readMetaData(0xc00007db60, 0xc00021c210, 0x0)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:984 +0x68
github.com/ncw/rclone/backend/webdav.(*Object).Update(0xc00007db60, 0x141ae00, 0xc0004f34c0, 0x142fcc0, 0xc0004f34e0, 0xc0002677c0, 0x1, 0x1, 0x20, 0x18)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:1087 +0x3ac
github.com/ncw/rclone/backend/webdav.(*Fs).Put(0xc00038a790, 0x141ae00, 0xc0004f34c0, 0x142fcc0, 0xc0004f34e0, 0xc0002677c0, 0x1, 0x1, 0x20, 0x1191d00, ...)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/webdav/webdav.go:605 +0x1a5
github.com/ncw/rclone/fs.Fs.Put-fm(0x141ae00, 0xc0004f34c0, 0x142fcc0, 0xc0004f34e0, 0xc0002677c0, 0x1, 0x1, 0x60, 0x80, 0xc0007fdba0, ...)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/cache/cache.go:1502 +0x88
github.com/ncw/rclone/backend/crypt.(*Fs).put(0xc0003b2960, 0x141ade0, 0xc00086c300, 0x7f4d38917bf0, 0xc0003c7320, 0xc0002677c0, 0x1, 0x1, 0xc0007fdc80, 0x10, ...)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/crypt/crypt.go:357 +0x194
github.com/ncw/rclone/backend/crypt.(*Fs).Put(0xc0003b2960, 0x141ade0, 0xc00086c300, 0x7f4d38917bf0, 0xc0003c7320, 0xc0002677c0, 0x1, 0x1, 0x43f04d, 0xc00003c2f8, ...)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/backend/crypt/crypt.go:389 +0xd5
github.com/ncw/rclone/fs/operations.Copy(0x1433aa0, 0xc0003b2960, 0x0, 0x0, 0xc000524550, 0x49, 0x14343a0, 0xc0003c7320, 0xf5fc169ecd8478c3, 0xf3779f082a204f2e, ...)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/fs/operations/operations.go:311 +0x13f6
github.com/ncw/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc000646000, 0xc000079d00, 0x1433aa0, 0xc0003b2960, 0xc0006460d8)
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/fs/sync/sync.go:290 +0x23c
created by github.com/ncw/rclone/fs/sync.(*syncCopyMove).startTransfers
        /var/tmp/portage/net-misc/rclone-1.46/work/rclone-1.46/src/github.com/ncw/rclone/fs/sync/sync.go:316 +0x9f
```

**Comment by comio** [comment]
I will try to reproduce with -vv.

Thanks

**Comment by comio** [comment]
I'm sorry. I applied a patch that set err=nil, causing the issue. Sorry for the noise.
