### ISSUE TITLE
Maybe broken on macOS Sierra

### ISSUE THREAD

**Issue by soffchen** [ncw/rclone#596]
> What is your rclone version (eg output from `rclone -V`)
`rclone: Version "v1.32"`
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
`macOS Sierra beta 3`
> Which cloud storage system are you using? (eg Google Drive)
`Google Drive`
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy smccd:The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv .`
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
```
$ rclone -v copy smccd:The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv .
2016/07/25 10:49:35 rclone: Version "v1.32" starting with parameters ["rclone" "-v" "copy" "smccd:The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv" "."]
2016/07/25 10:49:36 Local file system at /Users/soff/tmp: Modify window is 1s
2016/07/25 10:49:36 Google drive root '': Reading ""
2016/07/25 10:49:37 Google drive root '': Finished reading ""
2016/07/25 10:49:37 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv: Sizes differ
2016/07/25 10:49:37 Local file system at /Users/soff/tmp: Waiting for checks to finish
2016/07/25 10:49:37 Local file system at /Users/soff/tmp: Waiting for transfers to finish
```
rclone stops downloading at random size.

```
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 8388608 Jul 25 10:50 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
```
try again:
```
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
soff@imac5k ~/tmp $ ls -la The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
-rw-r--r-- 1 soff staff 2097152 Jul 25 10:49 The.Victorias.Secret.Fashion.Show.2015.1080p.HDTV.x264-BATV.mkv
```

**Comment by ncw** [comment]
Sorry I missed this issue when you posted it.

Looks strange!

Can you try with the `-v` flag and see if rclone logs anything else.

Did rclone finish with any sort of error?

Thanks

Nick

**Comment by soffchen** [comment]
Error message shown on sierra beta 4:

```
$ rclone copy smccd:Mac/ParallelsDesktop-11.2.1-32626.dmg .
2016/08/03 14:22:38 Local file system at /tmp: Waiting for checks to finish
2016/08/03 14:22:38 Local file system at /tmp: Waiting for transfers to finish
unexpected fault address 0x588158a75803
fatal error: fault
[signal 0xb code=0x1 addr=0x588158a75803 pc=0x588158a75803]

goroutine 122 [running]:
runtime.throw(0x817cf0, 0x5)
	/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc82052c880 sp=0xc82052c868
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc82052c8d0 sp=0xc82052c880
net/http.(*Transport).dial(0xc8200de480, 0x81a278, 0x3, 0xc820428420, 0x28, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:659 +0x96 fp=0xc82052c960 sp=0xc82052c8d0
net/http.(*Transport).dialConn(0xc8200de480, 0x0, 0xc820183300, 0x5, 0xc820428420, 0x28, 0xc82050c540, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:762 +0x1e3d fp=0xc82052cf00 sp=0xc82052c960
net/http.(*Transport).getConn.func4(0xc8200de480, 0x0, 0xc820183300, 0x5, 0xc820428420, 0x28, 0xc8200666c0)
	/usr/local/go/src/net/http/transport.go:706 +0x66 fp=0xc82052cf78 sp=0xc82052cf00
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82052cf80 sp=0xc82052cf78
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:708 +0x262

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc8201e5834)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc8201e5828)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/ncw/rclone/fs.(*syncCopyMove).stopTransfers(0xc8201e57a0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:328 +0xa3
github.com/ncw/rclone/fs.(*syncCopyMove).run(0xc8201e57a0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:448 +0x7dd
github.com/ncw/rclone/fs.CopyDir(0xd4b278, 0xc8203b19a0, 0xd4b1e0, 0xc820363140, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:484 +0x63
main.glob.func1(0xd4b278, 0xc8203b19a0, 0xd4b1e0, 0xc820363140, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:68 +0x4b
main.main()
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:525 +0xc04

goroutine 51 [chan receive]:
main.StartStats.func1()
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:428 +0x53
created by main.StartStats
	/home/ncw/Code/Go/src/github.com/ncw/rclone/rclone.go:431 +0x40

goroutine 15 [IO wait]:
net.runtime_pollWait(0xd89ee0, 0x72, 0xc82023e000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820479f00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820479f00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820479ea0, 0xc82023e000, 0x1000, 0x1000, 0x0, 0xd80028, 0xc8200680a0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82007a030, 0xc82023e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
github.com/mreiferson/go-httpclient.(*rwTimeoutConn).Read(0xc8203c51f0, 0xc82023e000, 0x1000, 0x1000, 0x4f6656775870492b, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/mreiferson/go-httpclient/httpclient.go:228 +0x17f
crypto/tls.(*block).readFromUntil(0xc8203b75c0, 0xd44318, 0xc8203c51f0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820374c00, 0x97a217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820374c00, 0xc820256000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xd4af60, 0xc820374c00, 0xc820338618, 0xc820256000, 0x1000, 0x1000, 0xa273, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1687 +0x67
net/http.(*noteEOFReader).Read(0xc8203aca60, 0xc820256000, 0x1000, 0x1000, 0xc820239d1d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820362f00)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820362f00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203385b0)
	/usr/local/go/src/net/http/transport.go:1073 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:857 +0x10a6

goroutine 16 [select]:
net/http.(*persistConn).writeLoop(0xc8203385b0)
	/usr/local/go/src/net/http/transport.go:1277 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:858 +0x10cb

goroutine 64 [select]:
net/http.(*Transport).getConn(0xc8200de480, 0xc8203d40e0, 0x0, 0xc820183300, 0x5, 0xc820428420, 0x28, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:711 +0x4ef
net/http.(*Transport).RoundTrip(0xc8200de480, 0xc8203d40e0, 0x56cd0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:311 +0x7e9
github.com/mreiferson/go-httpclient.(*Transport).RoundTrip(0xc82018e700, 0xc8203d40e0, 0xc8203d40e0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/mreiferson/go-httpclient/httpclient.go:201 +0x2d2
golang.org/x/oauth2.(*Transport).RoundTrip(0xc8201272f0, 0xc82042ea80, 0xc8201272f0, 0x0, 0x0)
	/home/ncw/Code/Go/src/golang.org/x/oauth2/transport.go:48 +0x234
net/http.send(0xc82042ea80, 0xd88fc8, 0xc8201272f0, 0x0, 0x0, 0x0, 0xc820182000, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc820127320, 0xc82042ea80, 0x0, 0x0, 0x0, 0xf25ae8, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc820127320, 0xc82042ea80, 0x979dc0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
net/http.(*Client).Do(0xc820127320, 0xc82042ea80, 0xc8201318d8, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:188 +0xff
github.com/ncw/rclone/drive.(*Object).httpResponse.func1(0xc8200672c0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:937 +0x52
github.com/ncw/rclone/pacer.(*Pacer).call(0xc8200672c0, 0xc8203dc150, 0xa, 0xf25a48, 0xc820428360)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:295 +0x8a
github.com/ncw/rclone/pacer.(*Pacer).Call(0xc8200672c0, 0xc8203dc150, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:318 +0x7a
github.com/ncw/rclone/drive.(*Object).httpResponse(0xc82017ea80, 0x814d68, 0x3, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:939 +0x2c2
github.com/ncw/rclone/drive.(*Object).Open(0xc82017ea80, 0x0, 0x0, 0x0, 0x0)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/drive/drive.go:979 +0x6d
github.com/ncw/rclone/fs.Copy(0xd4b278, 0xc8203b19a0, 0x0, 0x0, 0xd4b168, 0xc82017ea80, 0xd84888, 0xc8200d6980)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/operations.go:222 +0x33a
github.com/ncw/rclone/fs.(*syncCopyMove).pairCopier(0xc8201e57a0, 0xc820363b00, 0xd4b278, 0xc8203b19a0, 0xc8201e5828)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:236 +0x2c5
created by github.com/ncw/rclone/fs.(*syncCopyMove).startTransfers
	/home/ncw/Code/Go/src/github.com/ncw/rclone/fs/sync.go:319 +0x130

goroutine 121 [sleep]:
time.Sleep(0x77359400)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/ncw/rclone/pacer.(*Pacer).beginCall.func1(0xc8200672c0, 0x77359400)
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:200 +0x21
created by github.com/ncw/rclone/pacer.(*Pacer).beginCall
	/home/ncw/Code/Go/src/github.com/ncw/rclone/pacer/pacer.go:202 +0xaf
```

**Comment by ncw** [comment]
I suspect this is related to golang/go#16570 which looks like the fix will land in go 1.7 which should be released very soon.

I compiled a version of rclone with latest development go compiler (which will shortly be released as 1.7)

http://pub.rclone.org/rclone-v1.32-4-g57f8f1e-macOS-Sierra-fix.zip

Can you give that a go and see if it fixes it please?

Thanks

Nick

**Comment by soffchen** [comment]
WOW

It works well now.

Thanks :)

**Comment by ncw** [comment]
Great - thanks for testing.

The next version of rclone v1.33 will be built with go 1.7 so this will be fixed in that release.

**Comment by ncw** [comment]
go 1.7 has been released and has the fix in hopefully!

Here is a beta: http://pub.rclone.org/v1.32-20-g2ebeed6%CE%B2/

I'm going to close this now - please re-open if it isn't fixed.

Thanks
