### ISSUE TITLE
FUSE: panic in handler for ARMv7

### ISSUE THREAD

**Issue by kraiz** [ncw/rclone#813]
> What is your rclone version (eg output from rclone -V)

Version: `1.33-77` (but also tried older 1.33er betas and v1.33-63-gace1e21-tip-arm from #426)

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

debian 8 (jessie) 32bit armhf @ bananapi m2
```
$ getconf PAGESIZE
4096
$ cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 4 (v7l)
processor       : 0
BogoMIPS        : 1195.38
processor       : 1
BogoMIPS        : 1199.69
Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4
Hardware        : sun7i
Revision        : 0000
Serial          : 04c2<snip>d8
```

> Which cloud storage system are you using? (eg Google Drive)

amazon drive (unlimited trial)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

beta/rclone-v1.33-77-g93e8440-linux-arm/rclone mount amazon:/ /mnt/amazon -v --debug-fuse

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
beta/rclone-v1.33-77-g93e8440-linux-arm/rclone mount amazon:/ /mnt/amazon -v --debug-fuse
2016/10/23 13:10:54 rclone: Version "v1.33-77-g93e8440β" starting with parameters ["beta/rclone-v1.33-77-g93e8440-linux-arm/rclone" "mount" "amazon:/" "/mnt/amazon" "-v" "--debug-fuse"]
2016/10/23 13:10:58 amazon drive root '': Modify window not supported
2016/10/23 13:10:58 amazon drive root '': Root()
2016/10/23 13:11:10 fuse: <- Lookup [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=32569] "Dokumente"
2016/10/23 13:11:10 Dokumente: Dir.Lookup
2016/10/23 13:11:10 : Reading directory
2016/10/23 13:11:10 amazon drive root '': Reading ""
2016/10/23 13:11:11 amazon drive root '': Finished reading ""
2016/10/23 13:11:11 Dokumente: Dir.Lookup OK
2016/10/23 13:11:11 Dokumente: Dir.Attr
2016/10/23 13:11:11 fuse: -> [ID=0x2] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=15511363656845843624 size=0 mode=drwxr-xr-x}
2016/10/23 13:11:11 fuse: <- Lookup [ID=0x3 Node=0x2 Uid=1000 Gid=1000 Pid=32569] "README.md"
2016/10/23 13:11:11 Dokumente/README.md: Dir.Lookup
2016/10/23 13:11:11 Dokumente: Reading directory
2016/10/23 13:11:11 amazon drive root '': Reading "Dokumente/"
2016/10/23 13:11:12 amazon drive root '': Finished reading "Dokumente/"
2016/10/23 13:11:12 fuse: -> [ID=0x3] Lookup error=ENOENT
2016/10/23 13:11:12 fuse: <- Lookup [ID=0x4 Node=0x2 Uid=1000 Gid=1000 Pid=32569] "README.md"
2016/10/23 13:11:12 Dokumente/README.md: Dir.Lookup
2016/10/23 13:11:12 fuse: -> [ID=0x4] Lookup error=ENOENT
2016/10/23 13:11:12 fuse: <- Create [ID=0x5 Node=0x2 Uid=1000 Gid=1000 Pid=32569] "README.md" fl=OpenWriteOnly+OpenCreate+OpenExclusive+0x20000 mode=-rw-r--r-- umask=-----w--w-
2016/10/23 13:11:12 Dokumente/README.md: Dir.Create
2016/10/23 13:11:12 Dokumente/README.md: Dir.Create OK
2016/10/23 13:11:12 File.Attr
2016/10/23 13:11:12 fuse: panic in handler for Create [ID=0x5 Node=0x2 Uid=1000 Gid=1000 Pid=32569] "README.md" fl=OpenWriteOnly+OpenCreate+OpenExclusive+0x20000 mode=-rw-r--r-- umask=-----w--w-: runtime error: invalid memory address or ni
l pointer dereference
goroutine 68 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x90aa60, 0x1107c100, 0x11045f5c, 0x11045ef0)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:857 +0x98
panic(0x619f58, 0x10c20008)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:458 +0x454
sync/atomic.loadUint64(0x10f6a094, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.7.3.linux.amd64/src/sync/atomic/64bit_arm.go:10 +0x54
github.com/ncw/rclone/cmd/mount.(*File).Attr(0x10f6a090, 0xb6dae080, 0x10f80000, 0x10c6eab8, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/file.go:54 +0x150
bazil.org/fuse/fs.nodeAttr(0xb6dae080, 0x10f80000, 0x907ec0, 0x10f6a090, 0x10c6eab8, 0x0, 0x0)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:260 +0x160
bazil.org/fuse/fs.(*Server).saveLookup(0x10f857a0, 0xb6dae080, 0x10f80000, 0x10c6eaa0, 0x10f8b110, 0x10c52286, 0x9, 0x907ec0, 0x10f6a090, 0x0, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1404 +0x64
bazil.org/fuse/fs.(*Server).handleRequest(0x10f857a0, 0xb6dae080, 0x10f80000, 0x907e90, 0x10f7de80, 0x10f8b110, 0x90aa60, 0x1107c100, 0x11045f5c, 0x0, ...)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:1111 +0x1328
bazil.org/fuse/fs.(*Server).serve(0x10f857a0, 0x90aa60, 0x1107c100)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:878 +0x608
bazil.org/fuse/fs.(*Server).Serve.func1(0x10f857a0, 0x90aa60, 0x1107c100)
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:425 +0x78
created by bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/bazil.org/fuse/fs/serve.go:426 +0x548
2016/10/23 13:11:12 fuse: -> [ID=0x5] Create error=EIO: handler panicked: runtime error: invalid memory address or nil pointer dereference
```

Hi @ncw,

thanks for all this great work. After trying lot's of tools, i'm considering to be a rclone fanboy already :)

I stumbled over a device specific problem. Uploading via `copy` and `sync` works fine, but `mount` will panic when i copy a file (just some kB in size) into the mount point, f.e.:
```
$ cp README.md /mnt/amazon/Dokumente
cp: cannot create regular file ‘/mnt/amazon/Dokumente/README.md’: Input/output error
```
This works fine on my amd64-debian8!

I'm happy to test and debug this further with some instructions how to that :)

--
* updated log output with `--debug-fuse` enabled

**Comment by ncw** [comment]
I think this is an alignment of a 64 bit variable problem. From sync.Atomic docs

> On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned.

I've attempted to fix this in this beta

http://beta.rclone.org/v1.33-78-gc464cc6/ (will be uploaded in 15-30 mins)

Please test and report back!

Thanks

Nick

**Comment by kraiz** [comment]
Wow, that indeed fixes the panic. But there's another problem:
```
$ rclone-v1.33-78-gc464cc6-linux-arm/rclone mount amazon:/ /mnt/amazon -v --debug-fuse
2016/10/23 19:37:50 rclone: Version "v1.33-78-gc464cc6β" starting with parameters ["rclone-v1.33-78-gc464cc6-linux-arm/rclone" "mount" "amazon:/" "/mnt/amazon" "-v" "--debug-fuse"]
2016/10/23 19:37:53 amazon drive root '': Modify window not supported
2016/10/23 19:37:53 amazon drive root '': Root()
2016/10/23 19:37:58 fuse: <- Lookup [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=3047] "Dokumente"
2016/10/23 19:37:58 Dokumente: Dir.Lookup
2016/10/23 19:37:58 : Reading directory
2016/10/23 19:37:58 amazon drive root '': Reading ""
2016/10/23 19:37:58 amazon drive root '': Finished reading ""
2016/10/23 19:37:58 Dokumente: Dir.Lookup OK
2016/10/23 19:37:58 Dokumente: Dir.Attr
2016/10/23 19:37:58 fuse: -> [ID=0x2] Lookup 0x2 gen=0 valid=1m0s attr={valid=1m0s ino=15511363656845843624 size=0 mode=drwxr-xr-x}
2016/10/23 19:37:58 fuse: <- Lookup [ID=0x3 Node=0x2 Uid=1000 Gid=1000 Pid=3047] "README.md"
2016/10/23 19:37:58 Dokumente/README.md: Dir.Lookup
2016/10/23 19:37:58 Dokumente: Reading directory
2016/10/23 19:37:58 amazon drive root '': Reading "Dokumente/"
2016/10/23 19:37:59 amazon drive root '': Finished reading "Dokumente/"
2016/10/23 19:37:59 fuse: -> [ID=0x3] Lookup error=ENOENT
2016/10/23 19:37:59 fuse: <- Lookup [ID=0x4 Node=0x2 Uid=1000 Gid=1000 Pid=3047] "README.md"
2016/10/23 19:37:59 Dokumente/README.md: Dir.Lookup
2016/10/23 19:37:59 fuse: -> [ID=0x4] Lookup error=ENOENT
2016/10/23 19:37:59 fuse: <- Create [ID=0x5 Node=0x2 Uid=1000 Gid=1000 Pid=3047] "README.md" fl=OpenWriteOnly+OpenCreate+OpenExclusive+0x20000 mode=-rw-r--r-- umask=-----w--w-
2016/10/23 19:37:59 Dokumente/README.md: Dir.Create
2016/10/23 19:37:59 Dokumente/README.md: Dir.Create OK
2016/10/23 19:37:59 File.Attr
2016/10/23 19:37:59 fuse: -> [ID=0x5] Create {0x3 gen=0 valid=1m0s attr={valid=1m0s ino=2413903163892988006 size=0 mode=-rw-r--r--}} {0x1 fl=0}
2016/10/23 19:37:59 fuse: <- Getxattr [ID=0x6 Node=0x3 Uid=1000 Gid=1000 Pid=3047] "security.capability" 0 @0
2016/10/23 19:37:59 fuse: -> [ID=0x6] Getxattr error=operation not supported
2016/10/23 19:37:59 fuse: <- Write [ID=0x7 Node=0x3 Uid=1000 Gid=1000 Pid=3047] 0x1 2812 @0 fl=0 lock=0 ffl=OpenWriteOnly+0x20000
2016/10/23 19:37:59 Dokumente/README.md: WriteFileHandle.Write len=2812
2016/10/23 19:38:00 Dokumente/README.md: WriteFileHandle.Write OK (2812 bytes written)
2016/10/23 19:38:00 fuse: -> [ID=0x7] Write 2812
2016/10/23 19:38:00 fuse: <- Flush [ID=0x8 Node=0x3 Uid=1000 Gid=1000 Pid=3047] 0x1 fl=0x0 lk=0xd3fa932d08206d8c
2016/10/23 19:38:00 Dokumente/README.md: WriteFileHandle.Flush
2016/10/23 19:38:00 Dokumente/README.md: Upload error detected but not waiting since it only took 1.174977149s to upload: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=432 with Body length 3244
2016/10/23 19:38:00 Dokumente/README.md: WriteFileHandle.Flush error: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=432 with Body length 3244
2016/10/23 19:38:00 fuse: -> [ID=0x8] Flush error=EIO: Post https://content-eu.drive.amazonaws.com/cdproxy/nodes?suppress=deduplication: http: ContentLength=432 with Body length 3244
2016/10/23 19:38:00 fuse: <- Release [ID=0x9 Node=0x3 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenWriteOnly+0x20000 rfl=0 owner=0x0
2016/10/23 19:38:00 Dokumente/README.md: WriteFileHandle.Release nothing to do
2016/10/23 19:38:00 fuse: -> [ID=0x9] Release
```
This is consistent, retried the copy command and restarted the `mount` twice. I don't really get, what's the error in there...

**Comment by ncw** [comment]
Thanks for testing - glad that worked!

The next log is a different problem!  The problem being is that uploads don't work for amazon drive via `rclone mount` :-(

This is because Amazon need to know the size of the file in advance for the upload, but we don't know it until the end.  This could be fixed by buffering the file to disk for uploads (#711).

I've put a note to that effect in the docs 77b975d16fe2f52cb55302c69a6b1618a000d152

**Comment by kraiz** [comment]
Thanks for fixing.

Ahh, i see and understand the upload size problem. It's about Content-Length header, right? Sending no header fails and sending 50GB as Content-Length also fails, when uploaded file is just 40kB, right?
Then buffering would be the only option left...sure.

**Comment by ncw** [comment]
@kraiz yes you are right. Someone made an issue for this at #/824 so click the subscribe button there to receive notifications.

I'm going to close this now as the main issue is fixed.
