### ISSUE TITLE
Creating files on Drive on Raspberry Pi produces Input/output error

### ISSUE THREAD

**Issue by PythonNut** [ncw/rclone#814]
When filing an issue, please include the following information if
possible as well as a description of the problem.  Make sure you test
with the [latest beta of rclone](http://rclone.org/downloads/).

> What is your rclone version (eg output from `rclone -V`)

    rclone v1.33-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

    Arch Linux ARM (2016/10/23) on a Raspberry Pi 2 (armv7l)

> Which cloud storage system are you using? (eg Google Drive)

    Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

    rclone mount hmcdrive: /mnt/backup/HMCDrive
    touch  /mnt/backup/HMCDrive/testfile

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2016/10/23 23:35:16 rclone: Version "v1.33-DEV" starting with parameters ["rclone" "-v" "mount" "hmcdrive:" "/mnt/backup/HMCDrive"]
2016/10/23 23:35:17 Google drive root '': Modify window is 1ms
2016/10/23 23:35:17 Google drive root '': Root()
2016/10/23 23:36:03 : Dir.Attr
2016/10/23 23:36:07 HMCDrive: Dir.Lookup
2016/10/23 23:36:07 Google drive root '': Reading ""
2016/10/23 23:36:07 Google drive root '': Finished reading ""
2016/10/23 23:36:07 : Dir.ReadDirAll
2016/10/23 23:36:07 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:07 abc: Dir.Lookup
2016/10/23 23:36:07 : Dir.Attr
2016/10/23 23:36:07 : Dir.ReadDirAll
2016/10/23 23:36:07 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:09 ab: Dir.Lookup
2016/10/23 23:36:09 : Dir.Attr
2016/10/23 23:36:09 : Dir.ReadDirAll
2016/10/23 23:36:09 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:09 a: Dir.Lookup
2016/10/23 23:36:09 : Dir.Attr
2016/10/23 23:36:09 : Dir.ReadDirAll
2016/10/23 23:36:09 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 t: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll                                    
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 te: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 tes: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 test: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 testf: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:10 testfi: Dir.Lookup
2016/10/23 23:36:10 : Dir.Attr
2016/10/23 23:36:10 : Dir.ReadDirAll
2016/10/23 23:36:10 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:11 testfil: Dir.Lookup
2016/10/23 23:36:11 : Dir.Attr
2016/10/23 23:36:11 : Dir.ReadDirAll                                   
2016/10/23 23:36:11 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:11 testfile: Dir.Lookup
2016/10/23 23:36:11 : Dir.Attr
2016/10/23 23:36:11 : Dir.ReadDirAll
2016/10/23 23:36:11 : Dir.ReadDirAll OK with 8 entries
2016/10/23 23:36:11 testfile: Dir.Lookup
2016/10/23 23:36:11 testfile: Dir.Lookup
2016/10/23 23:36:11 testfile: Dir.Create
2016/10/23 23:36:11 testfile: Dir.Create OK
2016/10/23 23:36:11 File.Attr
2016/10/23 23:36:11 fuse: panic in handler for Create [ID=0x5c Node=0x1 Uid=1000 Gid=1000 Pid=2133] "testfile" fl=OpenWriteOnly+OpenCreate+OpenNonblock+0x20000
mode=-rw-r--r-- umask=-----w--w-: runtime error: invalid memory address or nil pointer dereference
goroutine 153 [running]:
bazil.org/fuse/fs.(*Server).serve.func2(0x8f9bc0, 0x10d8a680, 0x10c35f64, 0x10c35ef8)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:857 +0x98
panic(0x60ee90, 0x10c26008)
        /usr/lib/go/src/runtime/panic.go:458 +0x454
sync/atomic.loadUint64(0x10f8ced4, 0x0, 0x0)
        /usr/lib/go/src/sync/atomic/64bit_arm.go:10 +0x54
github.com/ncw/rclone/cmd/mount.(*File).Attr(0x10f8ced0, 0x74a8e340, 0x10[5/248] 0x10c94bf8, 0x0, 0x0)
        /build/rclone/src/rclone/.gopath/src/github.com/ncw/rclone/cmd/mount/file.go:52 +0x134
bazil.org/fuse/fs.nodeAttr(0x74a8e340, 0x10f80de0, 0x8f6fd0, 0x10f8ced0, 0x10c94bf8, 0x0, 0x0)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:260 +0x160
bazil.org/fuse/fs.(*Server).saveLookup(0x10d2d500, 0x74a8e340, 0x10f80de0, 0x10c94be0, 0x10d9e480, 0x10f82830, 0x8, 0x8f6fd0, 0x10f8ced0, 0x0, ...)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:1404 +0x64
bazil.org/fuse/fs.(*Server).handleRequest(0x10d2d500, 0x74a8e340, 0x10f80de0, 0x8f6fa0, 0x10d9e450, 0x10d9e480, 0x8f9bc0, 0x10d8a680, 0x10c35f64, 0x0, ...)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:1111 +0x1328
bazil.org/fuse/fs.(*Server).serve(0x10d2d500, 0x8f9bc0, 0x10d8a680)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:878 +0x608
bazil.org/fuse/fs.(*Server).Serve.func1(0x10d2d500, 0x8f9bc0, 0x10d8a680)
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:425 +0x78
created by bazil.org/fuse/fs.(*Server).Serve
        /build/rclone/src/rclone/.gopath/src/bazil.org/fuse/fs/serve.go:426 +0x548
2016/10/23 23:36:11 testfile: Dir.Lookup
```

**Comment by ncw** [comment]
I think I just fixed that bug in #813 - try this beta: http://beta.rclone.org/v1.33-79-g77b975d/

(I see you compiled from source - in that case do a `go get -u -v github.com/ncw/rclone`)

**Comment by ncw** [comment]
This was fixed in #813 so I'm going to close this one too.

**Comment by PythonNut** [comment]
Oh sorry. I actually got around to testing that beta last night, but then I fell asleep.

The issue has been resolved.

**Comment by ncw** [comment]
Great!
